import { Metadata } from 'next';
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Pricing from "../components/Pricing";
import FAQ from "../components/FAQ";
import Contact from "../components/Contact";
import Breadcrumb from "../components/Breadcrumb";
import Link from 'next/link';

export const metadata: Metadata = {
    title: "Custom HTML Email Signatures for Gmail | MailStora",
    description: "Professional, custom-coded HTML email signatures optimized for Gmail and Google Workspace. Avoid the 10KB limit and broken images.",
    alternates: {
        canonical: "https://mailstora.com/gmail-email-signature"
    }
};

const breadcrumbItems = [
    { label: 'Home', url: '/' },
    { label: 'HTML Email Signature Design', url: '/html-email-signature-design' },
    { label: 'Gmail Email Signatures', url: '/gmail-email-signature' }
];

const gmailSigFaqs = [
    {
        q: "Why does Gmail say my signature is too long?",
        a: "Gmail has a strict 10,000 character limit for signatures in the Settings panel. If your HTML is bloated with unnecessary CSS or inline images (base64 data), Gmail will reject it. We write hyper-lean HTML to stay well under this limit."
    },
    {
        q: "Why do my signature images disappear in Gmail?",
        a: "If you copy-paste images directly into Gmail settings, they are often uploaded as attachments. We host your images externally on a CDN and link to them in the HTML, so they always appear inline."
    },
    {
        q: "How do I install the HTML into Gmail?",
        a: "Gmail doesn't have an 'insert HTML' button. We provide a simple trick: open the rendered HTML file in your browser, select all (Ctrl+A / Cmd+A), copy, and paste directly into the Gmail signature box."
    }
];

export default async function GmailEmailSignaturePage() {
    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "Service",
        "@id": "https://mailstora.com/gmail-email-signature/#service",
        "name": "Custom Gmail Email Signatures",
        "serviceType": "Gmail HTML signature",
        "description": "HTML email signatures specifically coded and optimized for Gmail and Google Workspace.",
        "provider": { "@id": "https://mailstora.com/#organization" },
        "areaServed": "Worldwide",
        "audience": { "@type": "BusinessAudience", "audienceType": "Professionals and Corporations" },
        "offers": {
            "@type": "Offer",
            "priceCurrency": "USD",
            "price": "30",
            "url": "https://mailstora.com/gmail-email-signature/"
        }
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />
            <Navbar />
            
            <section className="sp-hero" style={{ paddingTop: '140px', paddingBottom: '80px', background: '#0f172a', color: '#fff' }}>
                <div className="container">
                    <Breadcrumb items={breadcrumbItems} />
                    <div className="text-center" style={{ maxWidth: '800px', margin: '0 auto', marginTop: '2rem' }}>
                        <h1 style={{ fontSize: '3rem', marginBottom: '1.5rem', lineHeight: '1.2' }}>Custom HTML Email Signatures for Gmail</h1>
                        <p style={{ fontSize: '1.2rem', color: '#94a3b8', marginBottom: '2rem' }}>
                            Get a professional, clickable signature designed perfectly for Gmail and Google Workspace, bypassing character limits and broken images.
                        </p>
                        <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem' }}>
                            <Link href="/quote" className="btn btn-primary" style={{ padding: '15px 30px', fontSize: '1.1rem' }}>Get Your Gmail Signature</Link>
                        </div>
                    </div>
                </div>
            </section>

            <section className="section">
                <div className="container">
                    <div className="row" style={{ maxWidth: '900px', margin: '0 auto' }}>
                        <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem' }}>Gmail Signature Limitations</h2>
                        <p style={{ fontSize: '1.1rem', color: '#475569', marginBottom: '1.5rem' }}>
                            While Gmail is modern, its signature editor is notoriously finicky. It strictly enforces a 10KB character limit, meaning messy code generated by automated tools is often rejected. Furthermore, pasting images directly can result in them showing up as attachments rather than part of the design.
                        </p>
                        
                        <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem', marginTop: '3rem' }}>How We Build for Google Workspace</h2>
                        <ul style={{ listStyle: 'none', padding: 0, marginBottom: '2rem' }}>
                            <li style={{ padding: '1.5rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem', borderLeft: '4px solid #ea4335' }}>
                                <h3 style={{ marginBottom: '0.5rem' }}>Lean, Minified HTML</h3>
                                <p style={{ color: '#64748b', margin: 0 }}>We hand-code the table structures to be as efficient as possible, ensuring you never hit the "signature is too long" error in Gmail settings.</p>
                            </li>
                            <li style={{ padding: '1.5rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem', borderLeft: '4px solid #ea4335' }}>
                                <h3 style={{ marginBottom: '0.5rem' }}>Externally Hosted Images</h3>
                                <p style={{ color: '#64748b', margin: 0 }}>We host your logos and headshots on our secure CDN (or yours) and link to them via absolute URLs, so they render instantly without attaching files to your emails.</p>
                            </li>
                            <li style={{ padding: '1.5rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem', borderLeft: '4px solid #ea4335' }}>
                                <h3 style={{ marginBottom: '0.5rem' }}>Browser-Copy Installation</h3>
                                <p style={{ color: '#64748b', margin: 0 }}>Since Gmail doesn't allow raw HTML upload, we format the output so it can be perfectly copied from a web browser and pasted into the editor without losing styling.</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>
            
            <FAQ data={gmailSigFaqs} />

            <Contact />
            <Footer />
        </>
    );
}
