const express = require('express');
const router = express.Router();
const controller = require('../controllers/quoteController');
router.get('/', controller.getAll);
router.post('/', controller.create);
router.get('/token/:token', controller.getOneByToken);
router.post('/:id/reply', controller.reply);
router.post('/:id/reply/client', controller.replyClient);
router.get('/:id', controller.getOne);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
router.post('/:id/convert', controller.convertToOrder);
module.exports = router;
