const express = require('express');
const router = express.Router();
const controller = require('../controllers/scheduleController');
router.get('/', controller.getAll);
router.get('/settings/availability', controller.getAvailability);
router.put('/settings/availability', controller.updateAvailability);
router.get('/available-slots', controller.getAvailableSlots);
router.post('/send-otp', controller.sendOtp);
router.post('/verify-otp', controller.verifyOtp);
router.post('/', controller.create);
router.get('/:id', controller.getOne);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
module.exports = router;
