import { Metadata } from 'next';
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Pricing from "../components/Pricing";
import FAQ from "../components/FAQ";
import Contact from "../components/Contact";
import Breadcrumb from "../components/Breadcrumb";
import Link from 'next/link';

export const metadata: Metadata = {
    title: "Fix Email Templates Broken in Outlook | MailStora",
    description: "Email broken in Outlook? We fix rendering issues, ghost padding, and broken images using VML and MSO conditional comments. Fast turnaround.",
    alternates: {
        canonical: "https://mailstora.com/outlook-email-rendering-fix"
    }
};

const breadcrumbItems = [
    { label: 'Home', url: '/' },
    { label: 'HTML Email Template Development', url: '/html-email-template-development' },
    { label: 'Outlook Email Rendering Fix', url: '/outlook-email-rendering-fix' }
];

const outlookFaqs = [
    {
        q: "Why does my email look fine in Gmail but terrible in Outlook?",
        a: "Since 2007, desktop versions of Outlook for Windows have used Microsoft Word's rendering engine to display HTML emails. This engine does not support modern CSS like flexbox, grid, max-width, or even basic background images."
    },
    {
        q: "Can you fix a template generated by a drag-and-drop builder?",
        a: "Yes. If your builder generated messy code that breaks in Outlook, we can extract the design, recode the HTML from scratch using tables, and inject it back into your platform."
    },
    {
        q: "Do you support the 'New Outlook' for Windows?",
        a: "Yes. Microsoft is slowly rolling out 'New Outlook', which is based on web technologies and renders much better. However, millions of corporate users are still on Outlook 2016, 2019, and 2021, so we code to support both."
    },
    {
        q: "How fast can you fix my broken email?",
        a: "We offer rush delivery for urgent campaigns. If you have an email scheduled to go out tomorrow, select our Rush option in the quote form, and we can usually fix it within 12-24 hours."
    }
];

export default async function OutlookRenderingFixPage() {
    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "Service",
        "@id": "https://mailstora.com/outlook-email-rendering-fix/#service",
        "name": "Outlook Email Rendering Fix",
        "serviceType": "HTML email rendering fix",
        "description": "Expert repair of HTML emails that render incorrectly in Microsoft Outlook.",
        "provider": { "@id": "https://mailstora.com/#organization" },
        "areaServed": "Worldwide",
        "audience": { "@type": "BusinessAudience", "audienceType": "Marketing Teams" },
        "offers": {
            "@type": "Offer",
            "priceCurrency": "USD",
            "price": "40",
            "url": "https://mailstora.com/outlook-email-rendering-fix/"
        }
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />
            <Navbar />
            
            <section className="sp-hero" style={{ paddingTop: '140px', paddingBottom: '80px', background: '#0f172a', color: '#fff' }}>
                <div className="container">
                    <Breadcrumb items={breadcrumbItems} />
                    <div className="text-center" style={{ maxWidth: '800px', margin: '0 auto', marginTop: '2rem' }}>
                        <div className="section-pill" style={{ display: 'inline-block', marginBottom: '1.5rem', background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', padding: '6px 16px', borderRadius: '30px', fontWeight: 'bold' }}>URGENT FIXES</div>
                        <h1 style={{ fontSize: '3rem', marginBottom: '1.5rem', lineHeight: '1.2' }}>Email Broken in Outlook? We Fix It.</h1>
                        <p style={{ fontSize: '1.2rem', color: '#94a3b8', marginBottom: '2rem' }}>
                            Send us your broken HTML. We will rewrite the code using ghost tables, VML, and MSO conditionals to ensure it looks perfect in every version of Outlook.
                        </p>
                        <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem' }}>
                            <Link href="/quote" className="btn btn-primary" style={{ padding: '15px 30px', fontSize: '1.1rem', background: '#ef4444', borderColor: '#ef4444' }}>Send Us Your HTML</Link>
                        </div>
                    </div>
                </div>
            </section>

            <section className="section">
                <div className="container">
                    <div className="row" style={{ maxWidth: '900px', margin: '0 auto' }}>
                        <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem' }}>Why Outlook Breaks Your Emails</h2>
                        <p style={{ fontSize: '1.1rem', color: '#475569', marginBottom: '1.5rem' }}>
                            Unlike web browsers, desktop versions of Microsoft Outlook (2016, 2019, 2021) use the <strong>Microsoft Word rendering engine</strong> to read HTML. This engine strips out standard web code like CSS grid, flexbox, border-radius, and background images. If your email was built by a web developer or a standard drag-and-drop tool, it will likely break in corporate Outlook environments.
                        </p>
                        
                        <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem', marginTop: '3rem' }}>Common Issues We Fix</h2>
                        <div style={{ border: '1px solid #e2e8f0', borderRadius: '8px', overflow: 'hidden', marginBottom: '3rem' }}>
                            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                                <thead>
                                    <tr style={{ background: '#f8fafc' }}>
                                        <th style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Symptom</th>
                                        <th style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>The Cause</th>
                                        <th style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Our Fix</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0', fontWeight: 'bold' }}>Images stretching wildly</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Outlook ignores max-width CSS</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Apply hard width attributes directly to image tags.</td>
                                    </tr>
                                    <tr>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0', fontWeight: 'bold' }}>Gaps between sliced images</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Line-height rendering bugs</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Use display:block and reset line-heights on table cells.</td>
                                    </tr>
                                    <tr>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0', fontWeight: 'bold' }}>Background images missing</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Word engine strips background-image CSS</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Implement Microsoft Vector Markup Language (VML).</td>
                                    </tr>
                                    <tr>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0', fontWeight: 'bold' }}>Email looks huge on high-res monitors</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Outlook DPI scaling</td>
                                        <td style={{ padding: '15px', borderBottom: '1px solid #e2e8f0' }}>Add the appropriate xmlns XML namespaces to the HTML tag.</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem' }}>Our Audit & Fix Process</h2>
                        <p style={{ fontSize: '1.1rem', color: '#475569', marginBottom: '1.5rem' }}>
                            Send us the broken HTML file or a link to your campaign. We will run it through Litmus to identify exactly which versions of Outlook are failing. We will then rebuild the structural framework using <strong>MSO Conditional Comments</strong> (code that only Outlook can read) to create bulletproof "Ghost Tables". The result is an email that looks identical to your design, but is structurally sound across all environments.
                        </p>
                    </div>
                </div>
            </section>
            
            <FAQ data={outlookFaqs} />

            <Contact />
            <Footer />
        </>
    );
}
