// Growth services beyond email: SEO, AEO and GEO, and Performance Marketing.
// Both pages use the standard service layout plus a grid of sub-service cards (growthCards.ts) rendered by ServicePage.
import type { ServiceData, RichContent } from "./services";
import { benefitItems, consult } from "./richContent";
import { SEO_CARDS, ADS_CARDS } from "./growthCards";

const IMG = "/images/media/generated/";

/* ─────────────────────────── SEO, AEO and GEO ─────────────────────────── */

const SEO_RICH: RichContent = {
    labels: {
        pains: ["Common Search Visibility Problems", "Why Your Site Is Not Being Found"],
        benefits: "Why Choose MailStora for SEO, AEO and GEO",
        projects: ["", "", ""],
        overview: "SEO, AEO and GEO Basics",
        process: ["SEO, AEO and GEO Process", "How We Grow Your Search Visibility"],
        related: ["Related Growth Services", "More Services", "From MailStora"],
    },
    cta: {
        eyebrow: "SEO, AEO and GEO Services",
        title: "Get Found on Google and Cited in AI Answers",
        text: "Share your website and goals and get a free audit summary and quote within 24 hours.",
        button: "Get My Free SEO Audit",
    },
    cta2: consult("SEO"),
    intro: {
        eyebrow: "Search in 2026",
        titleLead: "SEO, AEO and GEO",
        titleAccent: "in One Plan",
        image: IMG + "seo-aeo-geo-services-intro.webp",
        alt: "Google results page with an AI Overview citing the brand, next to an AI chat answer on a phone",
        image2: IMG + "seo-aeo-geo-services-phone.webp",
        alt2: "AI assistant answer on a phone citing a brand as the source",
        text: [
            "People no longer search in one place. They type into Google, read an AI Overview, ask ChatGPT or Perplexity, and only then click. If your brand is missing from any of those answers, you lose the customer before they reach your site.",
            "MailStora combines classic SEO with Answer Engine Optimisation (AEO) and Generative Engine Optimisation (GEO), so your pages rank on Google and are clear, trusted sources that AI tools can quote.",
        ],
        features: [
            { title: "Technical SEO", text: "Fast, crawlable, indexable pages with clean structure and schema." },
            { title: "On-page SEO", text: "Pages built around real search intent, with the right keywords and entities." },
            { title: "AEO", text: "Direct answers, FAQs and structured data for featured snippets and AI Overviews." },
            { title: "GEO", text: "Content, citations and brand signals that help AI assistants mention you." },
        ],
    },
    pains: {
        title: "Why Your Site Is Not Being Found",
        subtitle: "Most businesses come to us with one or more of these problems.",
        items: [
            { title: "Pages are not indexed", text: "Technical issues stop Google from crawling or indexing important pages." },
            { title: "Traffic is flat or falling", text: "Rankings slipped after updates, or AI Overviews now answer the query first." },
            { title: "Invisible in AI answers", text: "ChatGPT and Perplexity mention competitors but never your brand." },
            { title: "Content without a plan", text: "Blog posts are published with no keyword research or internal linking." },
        ],
    },
    offer: {
        title: "Monthly SEO, AEO and GEO",
        text: "An audit, a clear roadmap and monthly work across technical, on-page, content and AI visibility, with plain-English reporting.",
        priceLabel: "Pricing",
        price: "Custom",
        priceNote: "monthly retainer or one-off audit",
        cta: "Get My Free SEO Audit",
        image: IMG + "seo-aeo-geo-services-offer.webp",
        alt: "SEO, AEO and GEO package: technical SEO, AI-ready content and monthly reporting",
        items: [
            "Full technical SEO audit",
            "Keyword and entity research",
            "On-page optimisation of key pages",
            "Schema markup (FAQ, Product, Organization and more)",
            "Answer-first content for AEO",
            "AI visibility tracking for GEO",
            "Internal linking and content plan",
            "Monthly report in plain English",
        ],
    },
    benefits: {
        titleLead: "SEO, AEO and GEO",
        titleAccent: "Done Properly",
        subtitle: "One partner for search, AI visibility and the email marketing that converts the traffic.",
        items: benefitItems("project"),
    },
    projects: { subtitle: "", items: [] },
};

/* ─────────────────────────── Performance Marketing ─────────────────────────── */

const ADS_RICH: RichContent = {
    labels: {
        pains: ["Common Paid Ads Problems", "Why Your Ads Are Not Profitable"],
        benefits: "Why Choose MailStora for Performance Marketing",
        projects: ["", "", ""],
        overview: "Performance Marketing Basics",
        process: ["Performance Marketing Process", "How We Run Your Paid Campaigns"],
        related: ["Related Growth Services", "More Services", "From MailStora"],
    },
    cta: {
        eyebrow: "Performance Marketing",
        title: "Paid Ads That Pay for Themselves",
        text: "Tell us your platforms, budget and goals and get a free account review and quote within 24 hours.",
        button: "Get My Free Ads Review",
    },
    cta2: consult("Ads"),
    intro: {
        eyebrow: "Paid Growth",
        titleLead: "Performance Marketing",
        titleAccent: "Across Every Channel",
        image: IMG + "performance-marketing-intro.webp",
        alt: "Ads dashboard with ROAS and CPA next to a sponsored social ad on a phone",
        image2: IMG + "performance-marketing-phone.webp",
        alt2: "Sponsored social media ad on a phone",
        text: [
            "Paid ads can grow a brand fast, or burn through budget with little to show. The difference is tracking, testing and a clear plan for what happens after the click.",
            "MailStora plans and manages Meta, TikTok, Google and ChatGPT ads, sets up accurate tracking, and connects every campaign to email and SMS flows so more of your paid traffic turns into revenue.",
        ],
        features: [
            { title: "Meta ads", text: "Facebook and Instagram campaigns with creative testing and retargeting." },
            { title: "TikTok ads", text: "Native-style video ads and Spark Ads that fit the platform." },
            { title: "Google ads", text: "Search, Shopping, Performance Max and YouTube campaigns." },
            { title: "ChatGPT ads", text: "Early testing of ads inside AI chat, where available." },
        ],
    },
    pains: {
        title: "Why Your Ads Are Not Profitable",
        subtitle: "Most brands come to us when one of these starts eating the budget.",
        items: [
            { title: "Tracking is broken", text: "The pixel, Conversions API or GA4 do not match real orders, so decisions are guesses." },
            { title: "Creative is tired", text: "The same few ads run for months and costs keep rising." },
            { title: "No testing plan", text: "Budgets change on gut feel, and nobody knows what actually works." },
            { title: "Clicks without follow-up", text: "Visitors leave without buying and are never captured by email or retargeting." },
        ],
    },
    offer: {
        title: "Monthly Performance Marketing",
        text: "Strategy, campaign setup, creative testing, tracking and weekly optimisation across your chosen ad platforms, with clear monthly reporting.",
        priceLabel: "Pricing",
        price: "Custom",
        priceNote: "monthly management fee, plus your ad spend",
        cta: "Get My Free Ads Review",
        image: IMG + "performance-marketing-offer.webp",
        alt: "Performance marketing package: creative testing, pixel tracking and ROAS reporting",
        items: [
            "Account audit and strategy",
            "Pixel, Conversions API and GA4 setup",
            "Campaign structure and audiences",
            "Creative briefs and ad copy",
            "Weekly optimisation and testing",
            "Retargeting across channels",
            "Landing page and email follow-up advice",
            "Monthly ROAS and CPA report",
        ],
    },
    benefits: {
        titleLead: "Performance Marketing",
        titleAccent: "With Clear Numbers",
        subtitle: "One partner for ads and the email flows that turn clicks into customers.",
        items: benefitItems("campaign"),
    },
    projects: { subtitle: "", items: [] },
};

/* ─────────────────────────── Exports ─────────────────────────── */

export const GROWTH: Record<string, ServiceData> = {
    "seo-aeo-geo-services": {
        rich: SEO_RICH,
        cards: SEO_CARDS,
        category: "Search engine optimization",
        name: "SEO, AEO and GEO Services",
        serviceType: "Search engine optimization",
        summary: "Technical, on-page and content SEO plus answer engine and AI search optimisation.",
        metaTitle: "SEO, AEO and GEO Services: Rank on Google and in AI",
        metaDescription: "SEO, AEO and GEO services: technical SEO, on-page SEO, content, local and ecommerce SEO, plus answer engine and AI search optimisation for ChatGPT and Google AI Overviews.",
        eyebrow: "SEO · AEO · GEO",
        h1Lead: "SEO, AEO and GEO Services",
        h1Accent: "for Google and AI Search",
        lead: "MailStora helps brands get found wherever customers search: ranking on Google with technical and on-page SEO, winning direct answers with AEO, and being cited by ChatGPT, Perplexity and Google AI Overviews with GEO.",
        cta: "Get My Free SEO Audit",
        trust: ["Technical SEO audit", "AI search ready", "Schema markup", "Plain-English reports"],
        heroImage: IMG + "seo-aeo-geo-services-hero.webp",
        heroAlt: "Google results page with an AI Overview citing the brand on a laptop, and an AI chat answer on a phone",
        whatTitle: "What Are SEO, AEO and GEO Services?",
        what: [
            "SEO, AEO and GEO services improve how often your brand is found, chosen and quoted online. SEO helps your pages rank in search results, AEO helps them become the direct answer, and GEO helps AI assistants understand and mention your brand.",
            "MailStora runs all three as one plan, starting with a technical audit and keyword research, then improving your pages, content and brand signals month by month. Because we also build email flows, the traffic you win can be turned into subscribers and customers.",
        ],
        facts: [
            { label: "Covers", value: "Technical, on-page, content, off-page, local and ecommerce SEO" },
            { label: "AEO", value: "Snippets, FAQs, schema and AI Overviews" },
            { label: "GEO", value: "ChatGPT, Perplexity, Gemini, Copilot" },
            { label: "Tools", value: "Search Console, GA4, Semrush, Screaming Frog" },
            { label: "Reporting", value: "Monthly, in plain English" },
            { label: "Price", value: "Custom monthly retainer or one-off audit" },
        ],
        includedTitle: "What Our SEO, AEO and GEO Work Includes",
        included: [
            { title: "Technical SEO audit", text: "Crawling, indexing, speed, structure and schema checked and fixed." },
            { title: "Keyword research", text: "The searches and questions that bring buyers to your site." },
            { title: "On-page optimisation", text: "Titles, headings, content and internal links on key pages." },
            { title: "Content plan", text: "Topic clusters and guides that build authority." },
            { title: "AEO", text: "Answer-first content and FAQ schema for snippets and AI Overviews." },
            { title: "GEO", text: "Entity, citation and brand work for AI assistants." },
        ],
        galleryTitle: "",
        gallery: [],
        processLabel: "SEO",
        process: [
            { title: "Audit", text: "Technical, content and AI visibility audit of your site and competitors." },
            { title: "Roadmap", text: "A prioritised plan with clear milestones for the first 90 days." },
            { title: "Implement", text: "Technical fixes, page optimisation, content and schema, month by month." },
            { title: "Measure", text: "Monthly reporting on rankings, AI visibility, traffic and conversions." },
        ],
        platformsEyebrow: "Search and AI Platforms",
        platformsTitle: "Visibility Across Search Engines and AI Assistants",
        platformsSubtitle: "We optimise for the places your customers search and ask questions.",
        platforms: ["Google Search", "Google AI Overviews", "Bing", "ChatGPT", "Perplexity", "Gemini", "Microsoft Copilot", "Google Business Profile"],
        showWork: false,
        showPricing: false,
        related: ["performance-marketing", "shopify-development", "klaviyo-flow-setup", "social-media-management"],
        faqIntro: "Answers about MailStora SEO, AEO and GEO services.",
        faqs: [
            { q: "What is the difference between SEO, AEO and GEO?", a: "SEO helps your pages rank in search results. AEO helps your content become the direct answer in snippets, voice search and AI Overviews. GEO helps AI assistants such as ChatGPT and Perplexity understand and mention your brand." },
            { q: "Do I still need SEO if people use ChatGPT?", a: "Yes. AI tools and Google AI Overviews rely heavily on pages that search engines can crawl and trust, so strong SEO is the foundation for AEO and GEO." },
            { q: "Can you guarantee first place on Google or a ChatGPT mention?", a: "No honest provider can guarantee rankings or AI mentions. We improve the factors you can control and report progress clearly every month." },
            { q: "How long does SEO take to work?", a: "Technical fixes can help within weeks. Competitive rankings usually build over three to six months or more, depending on your site and market." },
            { q: "Do you work on Shopify and WordPress sites?", a: "Yes. We work on Shopify, WordPress, Webflow and custom sites, and can make technical changes directly or brief your developer." },
            { q: "How much do SEO, AEO and GEO services cost?", a: "Pricing is a custom monthly retainer or a one-off audit, based on site size and goals. Request a free quote to get a price." },
        ],
    },
    "performance-marketing": {
        rich: ADS_RICH,
        cards: ADS_CARDS,
        category: "Digital advertising",
        name: "Performance Marketing",
        serviceType: "Performance marketing",
        summary: "Meta, TikTok, Google and ChatGPT ads with accurate tracking and email follow-up.",
        metaTitle: "Performance Marketing: Meta, TikTok, Google and ChatGPT Ads",
        metaDescription: "Performance marketing for ecommerce and service brands: Meta ads, TikTok ads, Google ads and ChatGPT ads with pixel tracking, creative testing and ROAS reporting.",
        eyebrow: "Performance Marketing",
        h1Lead: "Performance Marketing",
        h1Accent: "Meta, TikTok, Google and ChatGPT Ads",
        lead: "MailStora plans and manages paid campaigns on Meta, TikTok, Google and ChatGPT, with accurate tracking, steady creative testing and email follow-up, so your ad spend turns into customers you can measure.",
        cta: "Get My Free Ads Review",
        trust: ["Meta and TikTok ads", "Google and ChatGPT ads", "Pixel and CAPI tracking", "Monthly ROAS reports"],
        heroImage: IMG + "performance-marketing-hero.webp",
        heroAlt: "Ads performance dashboard on a laptop and a sponsored social ad on a phone, with Meta, TikTok, Google Ads and ChatGPT icons",
        whatTitle: "What Is Included in Performance Marketing?",
        what: [
            "Performance marketing is paid advertising measured by results: sales, leads and signups. MailStora sets up tracking, builds campaigns, tests creative and moves budget toward what returns the most.",
            "Because MailStora also builds Klaviyo flows and email campaigns, your ads are connected to follow-up emails and SMS, so visitors who don't buy on the first click still have a clear path to purchase.",
        ],
        facts: [
            { label: "Platforms", value: "Meta, TikTok, Google, YouTube, ChatGPT (where available)" },
            { label: "Tracking", value: "Pixel, Conversions API, GA4, GTM" },
            { label: "Focus", value: "ROAS, CPA and revenue" },
            { label: "Creative", value: "Monthly testing of hooks, angles and formats" },
            { label: "Reporting", value: "Weekly checks, monthly report" },
            { label: "Price", value: "Monthly fee plus your ad spend" },
        ],
        includedTitle: "What We Handle Each Month",
        included: [
            { title: "Strategy", text: "Channels, budgets and goals planned around your margins." },
            { title: "Tracking setup", text: "Pixel, Conversions API, GA4 and GTM configured and checked." },
            { title: "Campaign builds", text: "Structure, audiences and ads on each platform." },
            { title: "Creative testing", text: "New hooks, angles and formats every month." },
            { title: "Optimisation", text: "Weekly bid, budget and audience changes." },
            { title: "Reporting", text: "Monthly ROAS, CPA and revenue report." },
        ],
        galleryTitle: "",
        gallery: [],
        processLabel: "Ads",
        process: [
            { title: "Audit", text: "Accounts, tracking, creative and past results reviewed." },
            { title: "Setup", text: "Tracking fixed and campaigns structured for testing." },
            { title: "Test", text: "Audiences and creatives tested to find a profitable cost per sale." },
            { title: "Scale", text: "Winning campaigns scaled, with monthly reporting." },
        ],
        platformsEyebrow: "Ad Platforms",
        platformsTitle: "Paid Campaigns on Every Major Platform",
        platformsSubtitle: "Campaigns run where your customers spend time, connected to your email and SMS flows.",
        platforms: ["Meta (Facebook and Instagram)", "TikTok", "Google Search", "Google Shopping", "Performance Max", "YouTube", "ChatGPT", "Microsoft Ads"],
        showWork: false,
        showPricing: false,
        related: ["seo-aeo-geo-services", "social-media-management", "klaviyo-flow-setup", "shopify-development"],
        faqIntro: "Answers about MailStora performance marketing.",
        faqs: [
            { q: "Which ad platforms do you manage?", a: "MailStora manages Meta (Facebook and Instagram), TikTok, Google Search, Shopping, Performance Max and YouTube ads, and runs ChatGPT ad tests where the format is available." },
            { q: "Can you run ads on ChatGPT?", a: "Ads inside ChatGPT are new and only available in limited markets at the time of writing. We run small tests where eligible and compare results with other channels before scaling." },
            { q: "Is ad spend included in your fee?", a: "No. Ad spend is paid directly to the platforms. Our fee covers strategy, setup, creative direction, optimisation and reporting." },
            { q: "How soon will I see results?", a: "Expect four to eight weeks of learning while tracking, audiences and creatives are tested. After that, budgets are scaled toward what works." },
            { q: "Do you guarantee a ROAS?", a: "No. Results depend on your product, margins, offer and market. We set clear targets together and report exactly what your spend returns." },
            { q: "How much does performance marketing cost?", a: "Management is a monthly fee based on platforms and spend. Request a free quote for a price." },
        ],
    },
};
