// Long-form ("rich") content for every service page except HTML Email Templates, which keeps its own block in services.ts.
// Same layout for every page: split intro, pain points, offer, benefits, projects, CTAs; only the words and images change.
import { siteConfig } from "../../../utils/siteConfig";
import type { RichContent } from "./services";

const { stats, upwork, founder } = siteConfig;
const IMG = "/images/media/cropped/";

// Benefits shared by every service, with the service noun swapped in
export const benefitItems = (noun: string) => [
    { title: "Direct access to the developer", text: `You work with ${founder.name} himself on every ${noun}, from brief to final revision.` },
    { title: "Fast, predictable turnaround", text: "Clear timelines agreed up front, with updates at every step and no missed deadlines." },
    { title: "Revisions included", text: "Revision rounds are built into every package, so you get exactly what you approved." },
    { title: "Built to reuse", text: "Clean, organised work your team can keep using long after delivery." },
    { title: "Clear communication", text: "Quick replies on WhatsApp, email or Upwork, in plain language." },
    { title: "Easy to work with", text: `A founder-led agency, ${upwork.badge} on Upwork and rated ${upwork.rating}/5 across ${upwork.reviews} reviews.` },
    { title: "Risk-free engagement", text: "A clear price and timeline before work starts, with no hidden fees." },
    { title: "Consistently dependable", text: `${upwork.jobSuccess} Job Success Score and ${stats.yearsExperience} years of experience.` },
];

export const consult = (topic: string) => ({
    eyebrow: `Free ${topic} Consultation`,
    title: `Not Sure What Your ${topic} Needs?`,
    text: "Book a free call with the founder to review your setup, platform and goals before you commit.",
    button: "Book a Free Consultation",
    href: "/schedule/",
});

export const RICH: Record<string, RichContent> = {
    "html-email-signature-design": {
        labels: {
            pains: ["Common Email Signature Problems", "Email Signature Problems That Hurt Your Brand"],
            benefits: "Why Choose MailStora for Email Signatures",
            projects: ["HTML Email Signature Portfolio", "HTML Email Signatures", "We Have Designed"],
            overview: "HTML Email Signature Basics",
            process: ["Email Signature Design Process", "How We Create Your HTML Email Signature"],
            related: ["Related Email Services", "More Email Services", "From MailStora"],
        },
        cta: {
            eyebrow: "HTML Email Signatures",
            title: "Get a Clickable Email Signature That Works in Gmail and Outlook",
            text: "Send your logo and details and get a free quote within 24 hours. Signatures from $25, with an install guide included.",
            button: "Order a Signature",
        },
        cta2: consult("Email Signature"),
        intro: {
            eyebrow: "Custom Email Signature Design",
            titleLead: "Professional Email Signatures",
            titleAccent: "Built for Every Inbox",
            text: [
                "Your email signature appears in every message your team sends, so a broken or plain-text signature quietly weakens your brand hundreds of times a day. A custom HTML email signature keeps your logo, contact links and social icons consistent everywhere.",
                "MailStora designs and codes clickable HTML email signatures that look sharp in Gmail, Outlook and Apple Mail, on desktop and mobile, with team versions for company-wide rollout.",
            ],
            image: "/images/media/generated/html-email-signature-design-intro.webp",
            alt: "Clickable, on-brand HTML email signature with photo, contact details, social icons and a promo banner in Gmail",
            image2: "/images/media/generated/html-email-signature-design-phone.webp",
            alt2: "HTML email signature on a phone",
            features: [
                { title: "On-brand design", text: "Your logo, colours and fonts in a clean layout that reads well at small sizes." },
                { title: "Clickable contact links", text: "Phone, email, website and booking links that open the right app." },
                { title: "Retina-sharp images", text: "Hosted high-resolution logos and photos that stay crisp on every screen." },
                { title: "Team-ready", text: "One master design with individual versions for every staff member." },
            ],
        },
        pains: {
            title: "Email Signature Problems That Hurt Your Brand",
            subtitle: "Most teams we help had one of these problems before switching to a custom HTML email signature.",
            items: [
                { title: "Signatures break in Outlook", text: "Images stretch, spacing collapses or the layout falls apart in Outlook." },
                { title: "Every staff member looks different", text: "Inconsistent fonts, colours and details make the company look disorganised." },
                { title: "Links are not clickable", text: "Phone numbers and social icons are just pictures that do nothing." },
                { title: "Logos look blurry", text: "Low-resolution images look pixelated on phones and high-density screens." },
            ],
        },
        offer: {
            title: "Custom HTML Email Signature",
            text: "A clickable, on-brand HTML email signature tested in Gmail, Outlook and Apple Mail, delivered with a step-by-step install guide.",
            priceLabel: "Starting at",
            price: "$25",
            priceNote: "per signature, one-time",
            cta: "Order a Signature",
            image: "/images/media/generated/html-email-signature-design-offer.webp",
            alt: "Custom HTML email signature: clickable, Outlook-safe and Gmail-ready",
            items: [
                "Custom branded signature design",
                "Clickable phone, email and website links",
                "Social icons and optional promo banner",
                "Retina-ready hosted images",
                "Tested in Gmail, Outlook and Apple Mail",
                "Mobile-friendly layout",
                "Install guide for every email client",
                "Team versions available",
            ],
        },
        benefits: {
            titleLead: "HTML Email Signature Design",
            titleAccent: "Without the Headaches",
            subtitle: "One designer-developer, clear communication and signatures that work the first time.",
            items: benefitItems("signature"),
        },
        projects: {
            subtitle: "Examples of HTML email signatures designed and coded for professionals and teams.",
            items: [
                { src: IMG + "mailstora-html-email-signature.webp", alt: "HTML email signature with banner", caption: "Signature with banner" },
                { src: IMG + "corporate-newsletter-email-signature.webp", alt: "Corporate email signature", caption: "Corporate signature" },
            ],
        },
    },

    "klaviyo-flow-setup": {
        labels: {
            pains: ["Common Klaviyo Flow Problems", "Klaviyo Automation Gaps That Lose Revenue"],
            benefits: "Why Choose MailStora for Klaviyo Flows",
            projects: ["Klaviyo Flow Email Portfolio", "Klaviyo Flow Emails", "We Have Built"],
            overview: "Klaviyo Flow Basics",
            process: ["Klaviyo Flow Setup Process", "How We Set Up Your Klaviyo Flows"],
            related: ["Related Klaviyo and Email Services", "More Email Services", "From MailStora"],
        },
        cta: {
            eyebrow: "Klaviyo Flow Setup",
            title: "Get Klaviyo Flows That Turn Subscribers Into Customers",
            text: "Tell us about your store and get a free quote within 24 hours for welcome, abandoned cart and post-purchase flows.",
            button: "Set Up My Flows",
        },
        cta2: consult("Klaviyo Account"),
        intro: {
            eyebrow: "Klaviyo Automation Setup",
            titleLead: "Klaviyo Flows That",
            titleAccent: "Sell While You Sleep",
            text: [
                "Klaviyo flows send the right email at the right moment automatically: when someone subscribes, abandons a cart, browses a product or places an order. For most ecommerce stores, these flows are the most profitable emails they send.",
                "MailStora builds each flow in your Klaviyo account with triggers, filters, delays and dynamic product blocks, and designs every email as a branded, hand-coded template.",
            ],
            image: "/images/media/generated/klaviyo-flow-setup-intro.webp",
            alt: "Klaviyo flow diagram: started checkout trigger, delays and reminder and reassurance emails",
            image2: "/images/media/generated/klaviyo-flow-setup-phone.webp",
            alt2: "Abandoned cart email from a Klaviyo flow on a phone",
            features: [
                { title: "Core ecommerce flows", text: "Welcome, abandoned cart, browse abandonment, post-purchase and win-back." },
                { title: "Smart triggers and filters", text: "Flows that reach the right people and skip the wrong ones." },
                { title: "Dynamic product blocks", text: "Cart items and recommendations pulled straight from your store." },
                { title: "Branded flow emails", text: "Every email designed and coded to match your brand." },
            ],
        },
        pains: {
            title: "Klaviyo Automation Gaps That Lose Revenue",
            subtitle: "Most stores we work with were missing sales because of one of these problems.",
            items: [
                { title: "Flows were never set up", text: "Only a basic welcome email runs, and carts and browsers get nothing." },
                { title: "Emails look generic", text: "Default Klaviyo templates that do not match the store's brand." },
                { title: "Wrong people get emails", text: "Missing filters send cart reminders to people who already bought." },
                { title: "No one knows what works", text: "Flows run untested for months without anyone checking results." },
            ],
        },
        offer: {
            title: "Klaviyo Flow Setup Package",
            text: "Your core Klaviyo flows built end to end, with branded emails, smart triggers and dynamic content, tested before launch.",
            priceLabel: "Pricing",
            price: "Custom",
            priceNote: "quoted per project",
            cta: "Set Up My Flows",
            image: "/images/media/generated/klaviyo-flow-setup-offer.webp",
            alt: "Klaviyo flow setup: core flows, smart triggers and dynamic product blocks",
            items: [
                "Welcome series",
                "Abandoned cart and checkout flow",
                "Browse abandonment flow",
                "Post-purchase and review flow",
                "Win-back and sunset flows",
                "Branded, hand-coded flow emails",
                "Dynamic product blocks",
                "Full testing before launch",
            ],
        },
        benefits: {
            titleLead: "Klaviyo Flow Setup",
            titleAccent: "Without the Headaches",
            subtitle: "One Klaviyo specialist, clear communication and flows that work from day one.",
            items: benefitItems("flow"),
        },
        projects: {
            subtitle: "Emails designed and built for Klaviyo welcome, cart, post-purchase and win-back flows.",
            items: [
                { src: IMG + "mailstora-welcome-email.webp", alt: "Welcome flow email", caption: "Welcome email" },
                { src: IMG + "mailstora-abandoned-cart-email.webp", alt: "Abandoned cart flow email", caption: "Abandoned cart" },
                { src: IMG + "mailstora-order-confirmation-email.webp", alt: "Post-purchase flow email", caption: "Post-purchase" },
                { src: IMG + "travel-win-back-email-template.webp", alt: "Win-back flow email", caption: "Win-back offer" },
                { src: IMG + "welcome-email-template.webp", alt: "Community welcome email", caption: "Community welcome" },
                { src: IMG + "abandoned-cart-email-template.webp", alt: "Cart reminder email", caption: "Cart reminder" },
            ],
        },
    },

    "klaviyo-campaign-management": {
        labels: {
            pains: ["Common Email Campaign Problems", "Email Campaign Problems That Waste Your List"],
            benefits: "Why Choose MailStora for Email Campaigns",
            projects: ["Email Campaign Portfolio", "Email Campaigns", "We Have Built"],
            overview: "Email Campaign Management Basics",
            process: ["Email Campaign Process", "How We Run Your Email Campaigns"],
            related: ["Related Email Marketing Services", "More Email Services", "From MailStora"],
        },
        cta: {
            eyebrow: "Klaviyo & Mailchimp Campaigns",
            title: "Get On-Brand Email Campaigns Without the Busywork",
            text: "Share your next offer or launch and get a free quote within 24 hours for design, build, segmentation and scheduling.",
            button: "Plan My Campaign",
        },
        cta2: consult("Email Campaign"),
        intro: {
            eyebrow: "Done-for-You Email Campaigns",
            titleLead: "Klaviyo & Mailchimp Campaigns,",
            titleAccent: "Planned and Built for You",
            text: [
                "Great campaigns need more than a nice design: the right audience, a subject line that gets opened, a layout that works in every inbox and a send time that suits your customers. Doing all of that every week takes time most teams do not have.",
                "MailStora plans, designs, codes, segments, tests and schedules your campaigns in Klaviyo or Mailchimp, then reports on the results so every send performs better than the last.",
            ],
            image: "/images/media/generated/klaviyo-campaign-management-intro.webp",
            alt: "Email campaign calendar with new arrivals, A/B test, newsletter and Black Friday campaigns",
            image2: "/images/media/generated/klaviyo-campaign-management-phone.webp",
            alt2: "Black Friday campaign email on a phone",
            features: [
                { title: "Campaign planning", text: "A send calendar built around launches, sales and seasons." },
                { title: "Design and HTML build", text: "On-brand, responsive campaign emails built as reusable templates." },
                { title: "Segments and A/B tests", text: "Targeted audiences and tested subject lines for better opens." },
                { title: "Scheduling and reports", text: "Sends timed for your audience, with results after every campaign." },
            ],
        },
        pains: {
            title: "Email Campaign Problems That Waste Your List",
            subtitle: "Brands usually come to us when one of these starts hurting results.",
            items: [
                { title: "Sends are irregular", text: "Campaigns go out when someone finds time, so the list goes cold." },
                { title: "Everyone gets every email", text: "No segmentation, so unsubscribes and spam complaints climb." },
                { title: "Emails look rushed", text: "Last-minute builder designs that do not match the brand." },
                { title: "No one checks results", text: "No A/B tests or reports, so nothing improves over time." },
            ],
        },
        offer: {
            title: "Managed Email Campaigns",
            text: "Campaign emails designed, built, segmented, tested and scheduled in Klaviyo or Mailchimp, one at a time or as a monthly package.",
            priceLabel: "Pricing",
            price: "Custom",
            priceNote: "per campaign or monthly",
            cta: "Plan My Campaign",
            image: "/images/media/generated/klaviyo-campaign-management-offer.webp",
            alt: "Managed email campaigns: content calendar, segmentation and reports",
            items: [
                "Campaign planning and calendar",
                "On-brand email design",
                "Responsive HTML build",
                "Audience segmentation",
                "A/B subject line testing",
                "QA across 50+ email clients",
                "Scheduling at the best send time",
                "Performance report after each send",
            ],
        },
        benefits: {
            titleLead: "Email Campaign Management",
            titleAccent: "Without the Headaches",
            subtitle: "One email specialist, clear communication and campaigns that go out on time.",
            items: benefitItems("campaign"),
        },
        projects: {
            subtitle: "Promotional, seasonal and content campaigns built for Klaviyo and Mailchimp.",
            items: [
                { src: IMG + "mailstora-black-friday-email.webp", alt: "Black Friday campaign", caption: "Black Friday sale" },
                { src: IMG + "mailstora-christmas-email.webp", alt: "Christmas campaign", caption: "Holiday campaign" },
                { src: IMG + "mailstora-event-invitation-email.webp", alt: "Event invitation campaign", caption: "Event invitation" },
                { src: IMG + "mailstora-marketing-tips-email-template.webp", alt: "Marketing tips newsletter", caption: "Content newsletter" },
                { src: IMG + "newsletter-email-template-coffee.webp", alt: "Lifestyle newsletter campaign", caption: "Lifestyle newsletter" },
                { src: IMG + "black-friday-sale-email-template.webp", alt: "Electronics sale campaign", caption: "Electronics sale" },
            ],
        },
    },

    "figma-to-html-email": {
        labels: {
            pains: ["Common Design to HTML Problems", "Why Email Designs Break After Coding"],
            benefits: "Why Choose MailStora for Figma to HTML",
            projects: ["Figma to HTML Email Portfolio", "Designs We Have", "Converted to HTML"],
            overview: "Figma to HTML Email Basics",
            process: ["Design to HTML Conversion Process", "How We Convert Your Design to HTML Email"],
            related: ["Related Email Development Services", "More Email Services", "From MailStora"],
        },
        cta: {
            eyebrow: "Figma & PSD to HTML Email",
            title: "Turn Your Figma or PSD Design Into Pixel-Perfect HTML Email",
            text: `Upload your design and get a free quote within 24 hours. Conversions from $40, delivered in ${stats.turnaround}.`,
            button: "Convert My Design",
        },
        cta2: consult("Email Design"),
        intro: {
            eyebrow: "Design to HTML Email",
            titleLead: "Your Email Design,",
            titleAccent: "Coded Exactly as Approved",
            text: [
                "Email HTML is very different from website HTML. A design that looks perfect in Figma or Photoshop has to be rebuilt with tables and inline styles, or it will break in Outlook, lose its fonts in Gmail and fall apart on mobile.",
                "MailStora hand-codes your Figma, PSD, Adobe XD or Illustrator design into responsive HTML that matches the original closely and works in every inbox, then sets it up for your email platform.",
            ],
            image: "/images/media/generated/figma-to-html-email-intro.webp",
            alt: "Figma email design on the left and the coded HTML email on the right, matching exactly",
            image2: "/images/media/generated/figma-to-html-email-phone.webp",
            alt2: "Coded HTML email from a Figma design on a phone",
            features: [
                { title: "Pixel-perfect accuracy", text: "Spacing, fonts, colours and images matched to your design." },
                { title: "Mobile layout included", text: "A responsive version even if you only designed for desktop." },
                { title: "Outlook-safe code", text: "VML and MSO fixes so backgrounds and buttons hold up." },
                { title: "ESP-ready modules", text: "Code split into editable blocks for your platform." },
            ],
        },
        pains: {
            title: "Why Email Designs Break After Coding",
            subtitle: "These are the problems designers and agencies most often bring to us.",
            items: [
                { title: "The code does not match", text: "Spacing, fonts and alignment drift away from the approved design." },
                { title: "Outlook ruins the layout", text: "Backgrounds disappear and columns collapse in Outlook." },
                { title: "No mobile version", text: "Desktop-only designs shrink into unreadable text on phones." },
                { title: "Hard to edit in the ESP", text: "One block of code that the team cannot update without a developer." },
            ],
        },
        offer: {
            title: "Figma to HTML Email Conversion",
            text: "Your Figma, PSD, XD or AI design hand-coded into responsive, Outlook-safe HTML email, tested in 50+ clients and ready for your ESP.",
            priceLabel: "Starting at",
            price: "$40",
            priceNote: "per design, one-time",
            cta: "Convert My Design",
            image: "/images/media/generated/figma-to-html-email-offer.webp",
            alt: "Figma to HTML email: any design file, pixel-perfect, mobile layout included",
            items: [
                "Figma, PSD, XD, AI and Sketch files",
                "Pixel-perfect design match",
                "Responsive mobile layout",
                "Web fonts with safe fallbacks",
                "Optimised, compressed images",
                "Outlook VML and MSO fixes",
                "Editable ESP modules",
                `Delivered in ${stats.turnaround}`,
            ],
        },
        benefits: {
            titleLead: "Figma to HTML Email Conversion",
            titleAccent: "Without the Headaches",
            subtitle: "One developer, clear communication and code that matches your design the first time.",
            items: benefitItems("conversion"),
        },
        projects: {
            subtitle: "Designs from many industries converted into responsive HTML email.",
            items: [
                { src: IMG + "real-estate-email-design.webp", alt: "Real estate email design", caption: "Real estate" },
                { src: IMG + "saas-software-email-design.webp", alt: "SaaS email design", caption: "SaaS" },
                { src: IMG + "healthcare-email-design.webp", alt: "Healthcare email design", caption: "Healthcare" },
                { src: IMG + "travel-hospitality-email-design.webp", alt: "Travel email design", caption: "Travel" },
                { src: IMG + "restaurant-food-email-design.webp", alt: "Restaurant email design", caption: "Restaurant" },
                { src: IMG + "fitness-wellness-email-design.webp", alt: "Fitness email design", caption: "Fitness" },
                { src: IMG + "education-email-design.webp", alt: "Education email design", caption: "Education" },
                { src: IMG + "events-conferences-email-design.webp", alt: "Event email design", caption: "Events" },
            ],
        },
    },

    "outlook-email-rendering-fix": {
        labels: {
            pains: ["Common Outlook Rendering Problems", "Outlook and Email Rendering Problems We Fix"],
            benefits: "Why Choose MailStora for Email Testing",
            projects: ["Email Testing Portfolio", "Emails We Have", "Tested and Repaired"],
            overview: "Outlook Rendering Basics",
            process: ["Email Testing and QA Process", "How We Test and Fix Your Emails"],
            related: ["Related Email Development Services", "More Email Services", "From MailStora"],
        },
        cta: {
            eyebrow: "Email Testing & Outlook Fixes",
            title: "Fix Your Broken Emails in Outlook, Gmail and Dark Mode",
            text: `Send your email and get a free quote within 24 hours. Most fixes delivered in ${stats.turnaround} with before and after screenshots.`,
            button: "Fix My Emails",
        },
        cta2: consult("Email Rendering"),
        intro: {
            eyebrow: "Email Testing & QA",
            titleLead: "Emails That Look Right",
            titleAccent: "in Every Inbox",
            text: [
                "Desktop Outlook renders email with Microsoft Word's engine, dark mode inverts colours and every mobile app has its own quirks. An email that looks perfect in one inbox can be broken in the one your best customers use.",
                "MailStora tests your emails in 50+ email clients and devices, then fixes Outlook bugs, dark mode issues, broken images and mobile layouts without changing your design.",
            ],
            image: "/images/media/generated/outlook-email-rendering-fix-intro.webp",
            alt: "Email broken in Outlook on the left and the fixed version on the right",
            image2: "/images/media/generated/outlook-email-rendering-fix-phone.webp",
            alt2: "Fixed email shown in dark mode on a phone",
            features: [
                { title: "50+ clients tested", text: "Desktop, web and mobile clients including every Outlook version." },
                { title: "Outlook-safe fixes", text: "VML, MSO conditionals and ghost tables that only Outlook reads." },
                { title: "Dark mode repairs", text: "Logos, text and colours that stay readable in dark mode." },
                { title: "Before and after report", text: "Screenshots so you can see exactly what changed." },
            ],
        },
        pains: {
            title: "Outlook and Email Rendering Problems We Fix",
            subtitle: "If any of these sound familiar, your subscribers are seeing a broken email.",
            items: [
                { title: "Ghost spacing in Outlook", text: "Random gaps, lines and padding appear between sections." },
                { title: "Background images vanish", text: "Hero images and colours disappear in desktop Outlook." },
                { title: "Dark mode ruins the design", text: "Logos disappear and text becomes unreadable." },
                { title: "Mobile layout breaks", text: "Columns do not stack and buttons are too small to tap." },
            ],
        },
        offer: {
            title: "Email Testing & Outlook Fix",
            text: "Your email tested in 50+ clients and devices, with every rendering issue repaired and a before and after report.",
            priceLabel: "Pricing",
            price: "Custom",
            priceNote: "quoted per email",
            cta: "Fix My Emails",
            image: "/images/media/generated/outlook-email-rendering-fix-offer.webp",
            alt: "Email testing and Outlook fixes: every Outlook version, dark mode, 50+ clients",
            items: [
                "Testing in 50+ email clients",
                "Outlook 2016, 2019, 365 and new Outlook",
                "Ghost spacing and column fixes",
                "Background image fixes with VML",
                "Dark mode colour and logo repairs",
                "Mobile layout fixes",
                "Bulletproof buttons and links",
                "Before and after screenshot report",
            ],
        },
        benefits: {
            titleLead: "Email Testing and Outlook Fixes",
            titleAccent: "Without the Headaches",
            subtitle: "One email developer who knows every Outlook quirk, with clear reports and quick turnaround.",
            items: benefitItems("fix"),
        },
        projects: {
            subtitle: "Emails tested and repaired so they render correctly in every client.",
            items: [
                { src: IMG + "mailstora-weekly-newsletter-email.webp", alt: "Newsletter layout fix", caption: "Newsletter layout" },
                { src: IMG + "education-email-design.webp", alt: "Education email mobile fix", caption: "Mobile layout" },
                { src: IMG + "healthcare-email-design.webp", alt: "Healthcare email dark mode fix", caption: "Dark mode" },
                { src: IMG + "nonprofit-charity-email-design.webp", alt: "Nonprofit email Outlook fix", caption: "Outlook backgrounds" },
                { src: IMG + "fitness-wellness-email-design.webp", alt: "Fitness email button fix", caption: "Button fixes" },
            ],
        },
    },

    "shopify-development": {
        labels: {
            pains: ["Common Shopify Store Problems", "Shopify Store Problems That Cost Sales"],
            benefits: "Why Choose MailStora for Shopify",
            projects: ["", "", ""],
            overview: "Shopify Development Basics",
            process: ["Shopify Development Process", "How We Improve Your Shopify Store"],
            related: ["Related Ecommerce Services", "More Services", "From MailStora"],
        },
        cta: {
            eyebrow: "Shopify Store Development",
            title: "Get a Faster, Better-Converting Shopify Store",
            text: "Share your store link and what you want to change, and get a free quote within 24 hours.",
            button: "Build My Store",
        },
        cta2: consult("Shopify Store"),
        intro: {
            eyebrow: "Shopify Theme Customisation",
            titleLead: "Shopify Stores Built to",
            titleAccent: "Convert and Connect",
            image: "/images/media/generated/shopify-development-intro.webp",
            alt: "Shopify store connected to Klaviyo: product page and matching email",
            image2: "/images/media/generated/shopify-development-phone.webp",
            alt2: "Back-in-stock email on a phone",
            text: [
                "A slow or generic Shopify store loses sales before shoppers reach checkout, and a store that is not connected to your email platform misses every abandoned cart and repeat purchase.",
                "MailStora customises your Shopify theme, speeds up slow pages, improves product and collection pages, and connects Shopify to Klaviyo so your store and email marketing work as one system.",
            ],
            features: [
                { title: "Theme customisation", text: "Custom sections and edits that match your brand." },
                { title: "Speed optimisation", text: "Faster pages through image, app and code clean-up." },
                { title: "Conversion-focused pages", text: "Product and collection pages that answer every question." },
                { title: "Klaviyo integration", text: "Forms, product feeds and tracking ready for email and SMS." },
            ],
        },
        pains: {
            title: "Shopify Store Problems That Cost Sales",
            subtitle: "These are the issues store owners most often ask us to fix.",
            items: [
                { title: "The store is slow", text: "Heavy images and too many apps make pages load slowly on mobile." },
                { title: "It looks like every other store", text: "A default theme that does not reflect the brand." },
                { title: "Product pages do not convert", text: "Missing details, reviews and trust signals stop shoppers buying." },
                { title: "Email is not connected", text: "Klaviyo is missing events, so cart and post-purchase emails fail." },
            ],
        },
        offer: {
            title: "Shopify Store Improvements",
            text: "Theme customisation, speed work, better product pages and a clean Klaviyo connection, scoped to what your store needs.",
            priceLabel: "Pricing",
            price: "Custom",
            priceNote: "quoted per project",
            cta: "Build My Store",
            image: "/images/media/generated/shopify-development-offer.webp",
            alt: "Shopify store improvements: theme work, faster pages and Klaviyo setup",
            items: [
                "Shopify theme customisation",
                "Custom sections and landing pages",
                "Product and collection page improvements",
                "Speed optimisation",
                "App setup and clean-up",
                "Klaviyo forms, feeds and tracking",
                "Mobile-first checkout experience",
                "Changes tested on a preview theme first",
            ],
        },
        benefits: {
            titleLead: "Shopify Development",
            titleAccent: "Without the Headaches",
            subtitle: "One developer who builds both your store and your email marketing.",
            items: benefitItems("project"),
        },
        projects: { subtitle: "", items: [] },
    },

    "social-media-management": {
        labels: {
            pains: ["Common Social Media Problems", "Social Media Problems That Stall Growth"],
            benefits: "Why Choose MailStora for Social Media",
            projects: ["", "", ""],
            overview: "Social Media Management Basics",
            process: ["Social Media Management Process", "How We Manage Your Social Media"],
            related: ["Related Marketing Services", "More Services", "From MailStora"],
        },
        cta: {
            eyebrow: "Social Media Management",
            title: "Keep Your Social Feeds Active, On-Brand and Growing",
            text: "Tell us about your brand and platforms and get a free quote within 24 hours for a monthly social media package.",
            button: "Grow My Socials",
        },
        cta2: consult("Social Media"),
        intro: {
            eyebrow: "Social Media for Ecommerce",
            titleLead: "Social Media Management",
            titleAccent: "Aligned With Your Emails",
            image: "/images/media/generated/social-media-management-intro.webp",
            alt: "Instagram-style feed planned alongside an email campaign calendar",
            image2: "/images/media/generated/social-media-management-phone.webp",
            alt2: "Instagram-style brand feed on a phone",
            text: [
                "An inactive or inconsistent social feed makes a growing brand look quiet, and posting every week takes time most founders do not have.",
                "MailStora plans, designs and schedules on-brand posts, stories and captions for ecommerce brands, timed with your email campaigns so every promotion reaches customers on every channel.",
            ],
            features: [
                { title: "Monthly content calendar", text: "Posts planned around your products, launches and seasons." },
                { title: "Branded designs", text: "Feed posts, carousels and stories that match your brand." },
                { title: "Captions and hashtags", text: "Clear captions with calls to action and researched hashtags." },
                { title: "Campaign alignment", text: "Social content timed with your email promotions." },
            ],
        },
        pains: {
            title: "Social Media Problems That Stall Growth",
            subtitle: "Most brands come to us when one of these starts holding them back.",
            items: [
                { title: "The feed goes quiet", text: "Weeks pass without a post, and reach drops." },
                { title: "Posts look inconsistent", text: "Different styles and fonts make the brand look unplanned." },
                { title: "No plan behind posting", text: "Content is made last minute with no link to sales or launches." },
                { title: "Email and social disconnected", text: "Promotions run on one channel while the other stays silent." },
            ],
        },
        offer: {
            title: "Monthly Social Media Management",
            text: "A monthly content calendar, branded posts and stories, captions, scheduling and reporting, aligned with your email campaigns.",
            priceLabel: "Pricing",
            price: "Custom",
            priceNote: "monthly package",
            cta: "Grow My Socials",
            image: "/images/media/generated/social-media-management-offer.webp",
            alt: "Monthly social media management: content calendar, branded posts and monthly report",
            items: [
                "Monthly content calendar",
                "Branded feed post designs",
                "Story and carousel designs",
                "Captions with calls to action",
                "Researched hashtags",
                "Scheduling at the best times",
                "Content aligned with email campaigns",
                "Monthly performance report",
            ],
        },
        benefits: {
            titleLead: "Social Media Management",
            titleAccent: "Without the Headaches",
            subtitle: "One partner for your email and social content, with clear plans and monthly reporting.",
            items: benefitItems("month of content"),
        },
        projects: { subtitle: "", items: [] },
    },
};

// Extra FAQs so every service page has a full FAQ section
export const EXTRA_FAQS: Record<string, { q: string; a: string }[]> = {
    "html-email-signature-design": [
        { q: "Can you add a promotional banner to my signature?", a: "Yes. MailStora can add a clickable banner to your HTML email signature to promote an offer, event or new product, and it can be swapped for new campaigns later." },
        { q: "Will the signature look right on mobile?", a: "Yes. Signatures are built with lightweight, table-based HTML and sized to stay readable and clickable in Gmail, Outlook and Apple Mail on phones." },
        { q: "Do you work from my existing signature design?", a: "Yes. MailStora can recode an existing design so it works properly, or create a new design from your logo and brand colours." },
        { q: "Can the signature include my photo?", a: "Yes. A round or square profile photo can be added, hosted at high resolution so it stays sharp on every screen." },
        { q: "How many revisions are included?", a: "Revision rounds are included with every signature package, so the final signature matches exactly what you approved." },
        { q: "Do you support Google Workspace and Microsoft 365?", a: "Yes. Signatures work in Google Workspace (Gmail) and Microsoft 365 (Outlook desktop, web and mobile), with setup steps for each." },
    ],
    "klaviyo-flow-setup": [
        { q: "What is the difference between a Klaviyo flow and a campaign?", a: "A Klaviyo flow is an automated series triggered by customer behaviour, such as a signup or abandoned cart. A campaign is a one-off email sent to a list or segment at a chosen time." },
        { q: "Can you improve flows I already have?", a: "Yes. MailStora can audit existing Klaviyo flows, fix triggers and filters, redesign the emails and add missing flows." },
        { q: "Do you set up Klaviyo SMS as well?", a: "Yes. SMS steps can be added to flows such as abandoned cart and welcome series, alongside the emails." },
        { q: "Will the flow emails be editable?", a: "Yes. Every flow email is built with editable sections so your team can change copy and images in Klaviyo later." },
        { q: "Do you write the flow email copy?", a: "MailStora can build from your copy or help shape subject lines and short email copy for each step of the flow." },
        { q: "How do I know the flows are working?", a: "Every path is tested with live data before launch, and you can review opens, clicks and revenue for each flow inside Klaviyo." },
    ],
    "klaviyo-campaign-management": [
        { q: "How many campaigns can you send each month?", a: "Monthly packages are sized to your needs, from a few key sends to a full weekly calendar. The number of campaigns is agreed before the month starts." },
        { q: "Do you design the campaign emails from scratch?", a: "Yes. Each campaign can be designed from scratch or built from your existing template library, always on-brand and responsive." },
        { q: "Will campaigns work in Outlook and Gmail?", a: "Yes. Every campaign is hand-coded and checked in Gmail, Outlook, Apple Mail and mobile apps before it is scheduled." },
        { q: "Can you manage campaigns for my agency's clients?", a: "Yes. MailStora can manage campaigns for agencies under white label, working inside each client's Klaviyo or Mailchimp account." },
        { q: "What do the campaign reports include?", a: "Each report summarises opens, clicks, conversions and revenue where available, with notes on what to test next." },
        { q: "Do I need to give access to my Klaviyo or Mailchimp account?", a: "Yes. Campaigns are built and scheduled in your account, so you add MailStora as a user and keep full ownership." },
    ],
    "figma-to-html-email": [
        { q: "Do you check my design before coding?", a: "Yes. Every design is reviewed for anything that will not render well in email, such as unsupported effects, and alternatives are suggested before coding starts." },
        { q: "Can you convert several email designs at once?", a: "Yes. Multiple designs can be converted together, and shared sections are built once as reusable modules." },
        { q: "Will the HTML work in Klaviyo and Mailchimp?", a: "Yes. The converted email is set up with editable sections and the correct merge tags for Klaviyo, Mailchimp, HubSpot or your platform." },
        { q: "How many revisions are included?", a: "Revision rounds are included with every conversion, so the final email matches your approved design." },
        { q: "Do you work with agencies and designers?", a: "Yes. MailStora converts designs for agencies and freelance designers, including under white label." },
        { q: "What if my design uses effects that email does not support?", a: "Effects such as complex animations or layered backgrounds are rebuilt with email-safe techniques or close alternatives, and you approve any changes first." },
    ],
    "outlook-email-rendering-fix": [
        { q: "What is VML and why is it needed for Outlook?", a: "VML (Vector Markup Language) is an old Microsoft format that desktop Outlook understands. It is used to show background images, rounded buttons and shapes that Outlook cannot display with normal CSS." },
        { q: "Do you test in real email clients?", a: "Yes. Emails are rendered across desktop, web and mobile email clients, including every current Outlook version, Gmail, Apple Mail and Yahoo Mail." },
        { q: "Can you fix emails built in Klaviyo or Mailchimp?", a: "Yes. MailStora can fix emails from Klaviyo, Mailchimp, HubSpot and other platforms, as long as the HTML can be exported or edited." },
        { q: "Why does Gmail clip my email?", a: "Gmail clips emails larger than about 102KB of HTML. MailStora reduces code size so the full email displays without the View entire message link." },
        { q: "Can you fix a whole library of templates?", a: "Yes. Several templates can be tested and fixed together, and shared modules are repaired once so every template benefits." },
        { q: "Will you change my design?", a: "No. Fixes keep your design as it is and only change the code needed to make it render correctly." },
    ],
    "shopify-development": [
        { q: "Do you build new Shopify stores from scratch?", a: "MailStora focuses on customising and improving existing Shopify stores. For a new store, the scope is agreed in a free consultation first." },
        { q: "Will changes affect my live store?", a: "No. Changes are built on a preview copy of your theme first and only go live after you approve them." },
        { q: "Can you add Klaviyo sign-up forms to my store?", a: "Yes. Pop-ups, embedded forms and footer sign-ups can be added and connected to Klaviyo lists." },
        { q: "Do you work with Shopify apps?", a: "Yes. Reviews, subscriptions, upsells and other apps can be installed, configured or removed if they slow the store down." },
    ],
    "social-media-management": [
        { q: "Do you create the post designs?", a: "Yes. Feed posts, carousels and stories are designed to match your brand for every month's calendar." },
        { q: "Do I approve posts before they go live?", a: "Yes. The monthly calendar and designs are shared for approval before anything is scheduled." },
        { q: "Can you grow my Instagram followers?", a: "MailStora focuses on consistent, on-brand content and organic growth. Results depend on your niche and audience, and progress is tracked in the monthly report." },
        { q: "Do you run paid social ads?", a: "The social media service covers organic content. Paid advertising can be discussed separately in a free consultation." },
    ],
};
