// Sub-service ("spoke") pages. Each supports a hub page and targets one distinct search intent.
// Built with the same layout as the hub pages; `spoke()` fills the fields the rich layout does not use.
import { siteConfig } from "../../../utils/siteConfig";
import { benefitItems, consult } from "./richContent";
import type { RichContent, ServiceData } from "./services";

const { stats, founder, upwork } = siteConfig;
const IMG = "/images/media/cropped/";
const founderLine = `${founder.name}, MailStora's founder (${stats.yearsExperience} years, ${upwork.jobSuccess} Job Success on Upwork)`;
const CLIENTS = ["Gmail", "Outlook 2016 / 2019 / 365", "New Outlook", "Apple Mail", "iOS Mail", "Yahoo Mail", "Samsung Email"];

type Spec = Omit<ServiceData, "included" | "includedTitle" | "gallery" | "galleryTitle" | "showWork" | "rich"> & {
    rich: Omit<RichContent, "cta2"> & { cta2?: RichContent["cta2"] };
    consultTopic: string;
};

function spoke({ rich, consultTopic, ...s }: Spec): ServiceData {
    return {
        ...s,
        includedTitle: "",
        included: [],
        galleryTitle: "",
        gallery: [],
        showWork: false,
        rich: { ...rich, cta2: rich.cta2 ?? consult(consultTopic) },
    };
}

const quoteCta = (eyebrow: string, title: string, text: string, button: string) => ({ eyebrow, title, text, button });

export const SPOKES: Record<string, ServiceData> = {
    /* ───────────────────────── Klaviyo email templates ───────────────────────── */
    "klaviyo-email-templates": spoke({
        name: "Klaviyo Email Templates",
        serviceType: "Klaviyo email template development",
        summary: "Custom Klaviyo templates with editable blocks and dynamic product content.",
        metaTitle: "Custom Klaviyo Email Templates, Hand-Coded | MailStora",
        metaDescription: `Klaviyo email templates built for Klaviyo's editor: editable blocks, dynamic product feeds and flow-ready layouts, tested in 50+ inboxes. From $40.`,
        eyebrow: "Klaviyo Email Templates",
        h1Lead: "Custom Klaviyo Email Templates",
        h1Accent: "Your Team Can Edit",
        lead: "MailStora builds custom Klaviyo email templates that keep your brand pixel-perfect while staying fully editable in Klaviyo's drag-and-drop editor, with dynamic product blocks ready for campaigns and flows.",
        cta: "Get a Klaviyo Template Quote",
        trust: ["Klaviyo editor compatible", "Dynamic product blocks", "Flow and campaign ready", `Delivered in ${stats.turnaround}`],
        heroImage: "/images/media/generated/klaviyo-email-templates-hero.webp",
        heroAlt: "Custom Klaviyo email template with editable blocks, shown on laptop and phone",
        whatTitle: "What Is a Custom Klaviyo Email Template?",
        what: [
            "A custom Klaviyo email template is an HTML email layout built specifically for Klaviyo, so it works with Klaviyo's editor, template tags and dynamic content instead of fighting them. Your team can reuse it for every campaign and flow without breaking the design.",
            `Every Klaviyo template is led and quality-checked by ${founderLine}. Sections are set up as editable blocks, product areas use Klaviyo's product feeds and catalog tags, and every template is tested in Gmail, Outlook and Apple Mail before it is uploaded to your account.`,
        ],
        facts: [
            { label: "Platform", value: "Klaviyo (campaigns and flows)" },
            { label: "Starting price", value: "$40 per template" },
            { label: "Delivery time", value: stats.turnaround },
            { label: "Editing", value: "Klaviyo drag-and-drop blocks" },
            { label: "Dynamic content", value: "Product feeds, catalog and profile tags" },
            { label: "Testing", value: "50+ email clients, light and dark mode" },
        ],
        priceFrom: "40",
        processLabel: "Klaviyo Template",
        process: [
            { title: "Share your design", text: "Send a Figma or PSD file, or your brand guide if the layout needs designing." },
            { title: "Build for Klaviyo", text: "The template is coded with Klaviyo editable blocks and template tags." },
            { title: "Test in every inbox", text: "It is tested in 50+ clients and with real Klaviyo preview data." },
            { title: "Upload and hand over", text: "The template is uploaded to your Klaviyo account, ready to use." },
        ],
        platformsEyebrow: "Klaviyo Template Compatibility",
        platformsTitle: "Klaviyo Templates Tested in Every Inbox",
        platformsSubtitle: "Built for Klaviyo campaigns and flows, connected to Shopify or WooCommerce product data, and tested in the inboxes your customers use.",
        platforms: ["Klaviyo", "Shopify", "WooCommerce", ...CLIENTS.slice(0, 4)],
        showPricing: true,
        related: ["klaviyo-flow-setup", "klaviyo-campaign-management", "html-email-template-development", "figma-to-html-email"],
        faqIntro: "Answers about custom Klaviyo email templates.",
        faqs: [
            { q: "Can I edit a custom Klaviyo template in the drag-and-drop editor?", a: "Yes. MailStora builds Klaviyo templates with editable blocks, so your team can change text, images and buttons in Klaviyo's editor without touching code." },
            { q: "Do Klaviyo templates support dynamic product blocks?", a: "Yes. Product areas can use Klaviyo product feeds, catalog lookups and event data, so abandoned cart and recommendation emails show the right products automatically." },
            { q: "Can one template be used for campaigns and flows?", a: "Yes. The same Klaviyo template can be reused across campaigns and flow emails, with sections switched on or off as needed." },
            { q: "How much does a Klaviyo email template cost?", a: `A custom Klaviyo email template starts at $40, and most are delivered in ${stats.turnaround}. Template packs for full flows are quoted per project.` },
            { q: "Will you upload the template to my Klaviyo account?", a: "Yes. With user access to your Klaviyo account, the template is uploaded, tested with live data and saved ready for your team." },
            { q: "Do Klaviyo templates work in Outlook and dark mode?", a: "Yes. Every template uses Outlook-safe code and is checked in dark mode, so it renders correctly for every subscriber." },
            { q: "What is the difference between a Klaviyo template and Klaviyo flow setup?", a: "A Klaviyo template is the email design. Klaviyo flow setup builds the automation around it: triggers, delays, filters and the full series of emails." },
            { q: "Can you rebuild my existing Klaviyo templates?", a: "Yes. Existing templates that break in Outlook or are hard to edit can be rebuilt with clean code and proper editable blocks." },
        ],
        rich: {
            labels: {
                pains: ["Common Klaviyo Template Problems", "Klaviyo Template Problems That Slow Your Team"],
                benefits: "Why Choose MailStora for Klaviyo Templates",
                projects: ["Klaviyo Email Template Portfolio", "Klaviyo Email Templates", "We Have Built"],
                overview: "Klaviyo Email Template Basics",
                process: ["Klaviyo Template Process", "How We Build Your Klaviyo Email Template"],
                related: ["Related Klaviyo Services", "More Klaviyo Services", "From MailStora"],
            },
            cta: quoteCta("Klaviyo Email Templates", "Get a Custom Klaviyo Template Your Team Can Reuse", "Send your design or brand guide and get a free quote within 24 hours. Templates from $40.", "Get a Klaviyo Template Quote"),
            intro: {
                eyebrow: "Klaviyo Template Design",
                titleLead: "Klaviyo Templates That Look Custom",
                titleAccent: "and Stay Editable",
                text: [
                    "Klaviyo's built-in templates are quick but generic, and fully coded templates often lose the drag-and-drop editing your team relies on. Most brands end up choosing between a great design and an easy workflow.",
                    "MailStora builds Klaviyo templates that give you both: a custom, on-brand layout coded to work with Klaviyo's editor, dynamic product blocks and template tags, so every campaign looks designed and takes minutes to build.",
                ],
                image: "/images/media/generated/klaviyo-email-templates-intro.webp",
                alt: "Custom template in the Klaviyo editor with text, image, product and button blocks",
                image2: "/images/media/generated/klaviyo-email-templates-phone.webp",
                alt2: "Klaviyo email template on a phone",
                features: [
                    { title: "Drag-and-drop editable", text: "Editable blocks your team can reorder and update in Klaviyo." },
                    { title: "Dynamic product content", text: "Product feeds, catalog and cart data built into the layout." },
                    { title: "Campaign and flow ready", text: "One template system for campaigns and automated flows." },
                    { title: "Outlook-safe code", text: "Hand-coded sections that hold up in Outlook and dark mode." },
                ],
            },
            pains: {
                title: "Klaviyo Template Problems That Slow Your Team",
                subtitle: "Brands usually come to us after one of these starts costing time or sales.",
                items: [
                    { title: "Default templates look generic", text: "Klaviyo's starter layouts make emails look like every other store." },
                    { title: "Custom code breaks the editor", text: "Coded templates that the team cannot edit without a developer." },
                    { title: "Products are added by hand", text: "No dynamic blocks, so every product email takes hours." },
                    { title: "Emails break in Outlook", text: "Klaviyo previews look fine, but Outlook subscribers see a broken layout." },
                ],
            },
            offer: {
                title: "Custom Klaviyo Email Template",
                text: "A custom, on-brand Klaviyo template with editable blocks and dynamic product content, uploaded to your account and tested in 50+ inboxes.",
                priceLabel: "Starting at",
                price: "$40",
                priceNote: "per template, one-time",
                cta: "Get a Klaviyo Template Quote",
                image: "/images/media/generated/klaviyo-email-templates-offer.webp",
                alt: "Custom Klaviyo template: editable blocks, product feeds and Outlook-safe code",
                items: [
                    "Custom design matched to your brand",
                    "Klaviyo drag-and-drop editable blocks",
                    "Dynamic product feed sections",
                    "Klaviyo template and profile tags",
                    "Responsive mobile layout",
                    "Outlook and dark mode fixes",
                    "Uploaded to your Klaviyo account",
                    `Delivered in ${stats.turnaround}`,
                ],
            },
            benefits: { titleLead: "Klaviyo Email Templates", titleAccent: "Without the Headaches", subtitle: "One Klaviyo specialist who designs, codes and uploads your templates.", items: benefitItems("Klaviyo template") },
            projects: {
                subtitle: "Klaviyo templates built for ecommerce campaigns and automated flows.",
                items: [
                    { src: IMG + "mailstora-fashion-email.webp", alt: "Klaviyo fashion template", caption: "Fashion launch" },
                    { src: IMG + "mailstora-abandoned-cart-email.webp", alt: "Klaviyo abandoned cart template", caption: "Abandoned cart" },
                    { src: IMG + "mailstora-black-friday-email.webp", alt: "Klaviyo Black Friday template", caption: "Black Friday" },
                    { src: IMG + "mailstora-welcome-email.webp", alt: "Klaviyo welcome template", caption: "Welcome email" },
                    { src: IMG + "fashion-ecommerce-email-template.webp", alt: "Klaviyo ecommerce template", caption: "Ecommerce promo" },
                ],
            },
        },
        consultTopic: "Klaviyo Template",
    }),

    /* ───────────────────────── Mailchimp email templates ───────────────────────── */
    "mailchimp-email-templates": spoke({
        name: "Mailchimp Email Templates",
        serviceType: "Mailchimp email template development",
        summary: "Coded Mailchimp templates with editable regions and merge tags.",
        metaTitle: "Custom Mailchimp Email Templates | MailStora",
        metaDescription: `Custom-coded Mailchimp email templates with mc:edit regions, repeatable sections and merge tags, tested in Outlook and Gmail. From $40, delivered in ${stats.turnaround}.`,
        eyebrow: "Mailchimp Email Templates",
        h1Lead: "Custom Mailchimp Email Templates",
        h1Accent: "Coded for Easy Editing",
        lead: "MailStora codes custom Mailchimp email templates with Mailchimp's template language, so every section is editable, repeatable and on-brand, and every email renders correctly in Outlook, Gmail and Apple Mail.",
        cta: "Get a Mailchimp Template Quote",
        trust: ["mc:edit editable regions", "Repeatable sections", "Merge tags set up", `Delivered in ${stats.turnaround}`],
        heroImage: "/images/media/generated/mailchimp-email-templates-hero.webp",
        heroAlt: "Custom Mailchimp template code with mc:edit regions and merge tags, and the email on laptop and phone",
        whatTitle: "What Is a Custom-Coded Mailchimp Template?",
        what: [
            "A custom-coded Mailchimp template is an HTML email written with Mailchimp's template language (mc:edit, mc:repeatable and mc:hideable), so Mailchimp's editor knows which text, images and sections your team can change. It gives you a unique design with the editing simplicity of Mailchimp.",
            `MailStora builds each Mailchimp template by hand, sets up merge tags such as *|FNAME|* and the required footer tags, and tests it in 50+ email clients. Every template is led and quality-checked by ${founderLine}.`,
        ],
        facts: [
            { label: "Platform", value: "Mailchimp (all plans with custom code)" },
            { label: "Starting price", value: "$40 per template" },
            { label: "Delivery time", value: stats.turnaround },
            { label: "Editing", value: "mc:edit, mc:repeatable, mc:hideable" },
            { label: "Personalisation", value: "Merge tags and audience fields" },
            { label: "Testing", value: "50+ email clients, light and dark mode" },
        ],
        priceFrom: "40",
        processLabel: "Mailchimp Template",
        process: [
            { title: "Share your design", text: "Send a design file, or your brand guide if you need the layout designed." },
            { title: "Code with Mailchimp tags", text: "Editable, repeatable and hideable regions are added to every section." },
            { title: "Test and QA", text: "The template is tested in 50+ clients and in Mailchimp's editor." },
            { title: "Import to Mailchimp", text: "The template is imported to your account, ready for campaigns." },
        ],
        platformsEyebrow: "Mailchimp Template Compatibility",
        platformsTitle: "Mailchimp Templates Tested in Every Inbox",
        platformsSubtitle: "Coded for Mailchimp's editor and audience fields, then tested in the email clients your subscribers use.",
        platforms: ["Mailchimp", "Mailchimp Classic Builder", "Shopify", ...CLIENTS.slice(0, 4)],
        showPricing: true,
        related: ["html-email-template-development", "klaviyo-campaign-management", "figma-to-html-email", "newsletter-email-templates"],
        faqIntro: "Answers about custom-coded Mailchimp email templates.",
        faqs: [
            { q: "Can I edit a custom-coded Mailchimp template myself?", a: "Yes. MailStora adds Mailchimp's mc:edit regions to every text and image area, so your team can edit content in Mailchimp without touching code." },
            { q: "What are repeatable sections in Mailchimp?", a: "Repeatable sections (mc:repeatable) let you duplicate a block, such as a product or article row, inside the Mailchimp editor. They make one template flexible enough for many campaigns." },
            { q: "Do custom templates work with Mailchimp's new builder?", a: "Mailchimp's newer builder has limited custom code support, so coded templates are used through the classic builder or code import. MailStora sets up the template in the option that suits your account." },
            { q: "Can you add merge tags and personalisation?", a: "Yes. Merge tags such as first name, and conditional content based on audience fields, can be built into the template." },
            { q: "How much does a Mailchimp email template cost?", a: `A custom Mailchimp email template starts at $40 and is usually delivered in ${stats.turnaround}.` },
            { q: "Will the template pass Mailchimp's requirements?", a: "Yes. Required footer tags such as the unsubscribe link and address are included, so the template is ready to send." },
            { q: "Can you convert my existing Mailchimp design to a coded template?", a: "Yes. An existing Mailchimp design can be rebuilt as a coded template with better Outlook support and cleaner editable regions." },
            { q: "Do Mailchimp templates work in Outlook?", a: "Yes. Every template uses table-based HTML with Outlook-specific fixes and is tested in Outlook 2016, 2019, 365 and the new Outlook." },
        ],
        rich: {
            labels: {
                pains: ["Common Mailchimp Template Problems", "Mailchimp Template Problems That Waste Time"],
                benefits: "Why Choose MailStora for Mailchimp Templates",
                projects: ["Mailchimp Email Template Portfolio", "Mailchimp Templates", "We Have Built"],
                overview: "Mailchimp Template Basics",
                process: ["Mailchimp Template Process", "How We Build Your Mailchimp Template"],
                related: ["Related Email Services", "More Email Services", "From MailStora"],
            },
            cta: quoteCta("Mailchimp Email Templates", "Get a Custom Mailchimp Template That Is Easy to Edit", "Send your design and get a free quote within 24 hours. Templates from $40.", "Get a Mailchimp Template Quote"),
            intro: {
                eyebrow: "Mailchimp Template Coding",
                titleLead: "Mailchimp Templates With a Custom Design",
                titleAccent: "and Simple Editing",
                text: [
                    "Mailchimp's drag-and-drop layouts are easy to use but hard to make unique, and a fully custom design usually becomes impossible for the team to edit. Emails end up looking generic or taking hours to update.",
                    "MailStora codes your design with Mailchimp's template language, so every text, image and section is editable, repeatable blocks let you add rows in seconds, and the code stays clean enough to render perfectly in Outlook.",
                ],
                image: "/images/media/generated/mailchimp-email-templates-intro.webp",
                alt: "Custom template in the Mailchimp editor with editable headline, image, product and button blocks",
                image2: "/images/media/generated/mailchimp-email-templates-phone.webp",
                alt2: "Mailchimp newsletter email on a phone",
                features: [
                    { title: "Editable regions", text: "mc:edit areas for every heading, paragraph, image and button." },
                    { title: "Repeatable blocks", text: "Duplicate product or article rows right inside Mailchimp." },
                    { title: "Merge tags ready", text: "Personalisation and required footer tags set up for you." },
                    { title: "Clean, tested code", text: "Table-based HTML tested in Outlook, Gmail and Apple Mail." },
                ],
            },
            pains: {
                title: "Mailchimp Template Problems That Waste Time",
                subtitle: "These are the Mailchimp issues teams most often ask us to solve.",
                items: [
                    { title: "Every campaign looks the same", text: "Builder layouts that make the brand look generic." },
                    { title: "The coded template is locked", text: "Custom code without editable regions, so every change needs a developer." },
                    { title: "Outlook breaks the layout", text: "Mailchimp previews look fine, but Outlook shows gaps and stretched images." },
                    { title: "Building a campaign takes hours", text: "No repeatable sections, so rows are rebuilt by hand every time." },
                ],
            },
            offer: {
                title: "Custom Mailchimp Email Template",
                text: "A custom, on-brand Mailchimp template with editable and repeatable regions, merge tags and Outlook-safe code, imported to your account.",
                priceLabel: "Starting at",
                price: "$40",
                priceNote: "per template, one-time",
                cta: "Get a Mailchimp Template Quote",
                image: "/images/media/generated/mailchimp-email-templates-offer.webp",
                alt: "Custom Mailchimp template: mc:edit regions, repeatable sections and merge tags",
                items: [
                    "Custom design matched to your brand",
                    "mc:edit editable regions",
                    "mc:repeatable and mc:hideable sections",
                    "Merge tags and footer tags",
                    "Responsive mobile layout",
                    "Outlook and dark mode fixes",
                    "Imported to your Mailchimp account",
                    `Delivered in ${stats.turnaround}`,
                ],
            },
            benefits: { titleLead: "Mailchimp Email Templates", titleAccent: "Without the Headaches", subtitle: "One developer who knows Mailchimp's template language inside out.", items: benefitItems("Mailchimp template") },
            projects: {
                subtitle: "Newsletter, promotional and content templates coded for Mailchimp.",
                items: [
                    { src: IMG + "mailstora-marketing-tips-email-template.webp", alt: "Mailchimp content newsletter", caption: "Content newsletter" },
                    { src: IMG + "newsletter-email-template-coffee.webp", alt: "Mailchimp lifestyle newsletter", caption: "Lifestyle newsletter" },
                    { src: IMG + "mailstora-real-estate-email.webp", alt: "Mailchimp real estate email", caption: "Real estate listing" },
                    { src: IMG + "black-friday-sale-email-template.webp", alt: "Mailchimp sale email", caption: "Sale campaign" },
                ],
            },
        },
        consultTopic: "Mailchimp Template",
    }),

    /* ───────────────────────── HubSpot email templates ───────────────────────── */
    "hubspot-email-templates": spoke({
        name: "HubSpot Email Templates",
        serviceType: "HubSpot email template development",
        summary: "HubSpot drag-and-drop templates with custom, reusable modules.",
        metaTitle: "Custom HubSpot Email Templates & Modules | MailStora",
        metaDescription: "HubSpot email templates with drag-and-drop areas and reusable HubL modules, so marketers edit freely without breaking the design. Tested in 50+ inboxes.",
        eyebrow: "HubSpot Email Templates",
        h1Lead: "Custom HubSpot Email Templates",
        h1Accent: "Built With Reusable Modules",
        lead: "MailStora builds custom HubSpot email templates with drag-and-drop areas and reusable HubL modules, so your marketing team can build on-brand emails in HubSpot's editor without breaking the layout.",
        cta: "Get a HubSpot Template Quote",
        trust: ["Drag-and-drop areas", "Custom HubL modules", "Brand-locked styling", "Tested in 50+ inboxes"],
        heroImage: "/images/media/generated/hubspot-email-templates-hero.webp",
        heroAlt: "Reusable HubL module code with a HubSpot marketing email on laptop and phone",
        whatTitle: "What Is a Custom HubSpot Email Template?",
        what: [
            "A custom HubSpot email template is a coded template built with HubSpot's design tools, using drag-and-drop areas and custom modules written in HubL, HubSpot's template language. Marketers add, remove and edit modules in the email editor while brand fonts, colours and spacing stay locked.",
            `MailStora designs and codes each module to be reusable across newsletters, nurture emails and announcements, and tests every template in Outlook, Gmail and Apple Mail. Every build is handled by ${founderLine}.`,
        ],
        facts: [
            { label: "Platform", value: "HubSpot Marketing Hub" },
            { label: "Build", value: "Drag-and-drop areas and HubL modules" },
            { label: "Editing", value: "HubSpot email editor" },
            { label: "Personalisation", value: "Contact and company tokens" },
            { label: "Testing", value: "50+ email clients, light and dark mode" },
            { label: "Price", value: "Quoted per project" },
        ],
        processLabel: "HubSpot Template",
        process: [
            { title: "Plan the modules", text: "Your email types are reviewed and a reusable module library is planned." },
            { title: "Build in HubSpot", text: "Modules and the drag-and-drop template are coded in HubSpot's design manager." },
            { title: "Test and QA", text: "Every module is tested in 50+ clients and in HubSpot's editor." },
            { title: "Train your team", text: "You get a short guide to building emails with the new modules." },
        ],
        platformsEyebrow: "HubSpot Template Compatibility",
        platformsTitle: "HubSpot Templates Tested in Every Inbox",
        platformsSubtitle: "Built in HubSpot's design manager and tested in the email clients your B2B contacts use.",
        platforms: ["HubSpot Marketing Hub", "HubSpot CRM", "Salesforce", ...CLIENTS.slice(0, 4)],
        showPricing: false,
        related: ["html-email-template-development", "newsletter-email-templates", "figma-to-html-email", "white-label-email-development"],
        faqIntro: "Answers about custom HubSpot email templates and modules.",
        faqs: [
            { q: "What is a HubSpot email module?", a: "A HubSpot module is a reusable, editable block, such as a hero, article row or CTA, coded in HubL. Marketers drag modules into emails and edit their content without changing the design." },
            { q: "Can my team still use HubSpot's drag-and-drop editor?", a: "Yes. MailStora builds templates with drag-and-drop areas, so your team can add, reorder and remove modules in HubSpot's email editor." },
            { q: "Do HubSpot templates support personalisation tokens?", a: "Yes. Contact, company and deal tokens can be used in any module, with fallback values for missing data." },
            { q: "Which HubSpot plan do I need?", a: "Custom coded email templates need HubSpot Marketing Hub Professional or Enterprise, which include the design manager." },
            { q: "Will HubSpot emails render correctly in Outlook?", a: "Yes. Modules are coded with table-based HTML and Outlook fixes, and tested in Outlook 2016, 2019, 365 and the new Outlook." },
            { q: "How much does a HubSpot email template cost?", a: "HubSpot templates are quoted per project, based on how many modules and email types you need. Request a free quote with your designs." },
            { q: "Can you convert our existing HubSpot emails into modules?", a: "Yes. Existing HubSpot emails can be rebuilt as a clean module library so future emails are faster to create." },
        ],
        rich: {
            labels: {
                pains: ["Common HubSpot Email Problems", "HubSpot Email Problems That Slow Marketing"],
                benefits: "Why Choose MailStora for HubSpot Templates",
                projects: ["HubSpot Email Template Portfolio", "HubSpot-Style Email Templates", "We Have Built"],
                overview: "HubSpot Email Template Basics",
                process: ["HubSpot Template Process", "How We Build Your HubSpot Email Templates"],
                related: ["Related Email Services", "More Email Services", "From MailStora"],
            },
            cta: quoteCta("HubSpot Email Templates", "Get a HubSpot Module Library Your Marketers Love", "Share your email types and designs and get a free quote within 24 hours.", "Get a HubSpot Template Quote"),
            intro: {
                eyebrow: "HubSpot Module Development",
                titleLead: "HubSpot Email Templates That Scale",
                titleAccent: "With Your Marketing Team",
                text: [
                    "HubSpot's default email templates are limited, and marketers who customise them often break spacing, fonts and brand colours. Over time every email looks slightly different.",
                    "MailStora builds a library of custom, reusable HubL modules inside a drag-and-drop template. Your team builds any email from approved blocks, and the brand stays consistent in every send.",
                ],
                image: "/images/media/generated/hubspot-email-templates-intro.webp",
                alt: "HubSpot module library: hero, feature row, testimonial and CTA modules building an email",
                image2: "/images/media/generated/hubspot-email-templates-phone.webp",
                alt2: "HubSpot product update email on a phone",
                features: [
                    { title: "Reusable HubL modules", text: "Hero, article, feature, CTA and footer modules built once." },
                    { title: "Drag-and-drop areas", text: "Marketers arrange modules freely in HubSpot's editor." },
                    { title: "Brand-locked styling", text: "Fonts, colours and spacing that editors cannot break." },
                    { title: "Personalisation tokens", text: "Contact and company data with sensible fallbacks." },
                ],
            },
            pains: {
                title: "HubSpot Email Problems That Slow Marketing",
                subtitle: "B2B teams usually come to us when one of these starts slowing launches.",
                items: [
                    { title: "Emails drift off-brand", text: "Each marketer changes fonts and spacing, so emails never match." },
                    { title: "Default modules are limited", text: "HubSpot's built-in blocks cannot create the layouts you need." },
                    { title: "Every email is built from scratch", text: "No reusable library, so launches wait on design and code." },
                    { title: "Outlook shows a broken email", text: "Enterprise contacts on Outlook see gaps and stretched images." },
                ],
            },
            offer: {
                title: "HubSpot Template and Module Library",
                text: "A custom HubSpot drag-and-drop template with a library of reusable HubL modules, tested in 50+ inboxes and ready for your team.",
                priceLabel: "Pricing",
                price: "Custom",
                priceNote: "quoted per project",
                cta: "Get a HubSpot Template Quote",
                image: "/images/media/generated/hubspot-email-templates-offer.webp",
                alt: "HubSpot template and module library: HubL modules, brand-locked and personalised",
                items: [
                    "Custom drag-and-drop template",
                    "Reusable HubL module library",
                    "Brand-locked fonts and colours",
                    "Personalisation tokens with fallbacks",
                    "Responsive mobile layout",
                    "Outlook and dark mode fixes",
                    "Built in your HubSpot design manager",
                    "Team guide for using modules",
                ],
            },
            benefits: { titleLead: "HubSpot Email Templates", titleAccent: "Without the Headaches", subtitle: "One developer who builds HubSpot modules your marketers can use confidently.", items: benefitItems("HubSpot template") },
            projects: {
                subtitle: "B2B and SaaS email designs of the kind we build as HubSpot modules.",
                items: [
                    { src: IMG + "saas-product-update-email-template.webp", alt: "SaaS product update email", caption: "Product update" },
                    { src: IMG + "mailstora-welcome-email.webp", alt: "SaaS welcome email", caption: "Onboarding" },
                    { src: IMG + "mailstora-event-invitation-email.webp", alt: "Event invitation email", caption: "Event invitation" },
                    { src: IMG + "mailstora-marketing-tips-email-template.webp", alt: "B2B newsletter", caption: "B2B newsletter" },
                ],
            },
        },
        consultTopic: "HubSpot Email",
    }),

    /* ───────────────────────── Newsletter email templates ───────────────────────── */
    "newsletter-email-templates": spoke({
        name: "Newsletter Email Templates",
        serviceType: "Newsletter email template development",
        summary: "Modular newsletter templates your team can fill in every week.",
        metaTitle: "Custom Newsletter Email Templates | MailStora",
        metaDescription: `Custom newsletter email templates with modular article, product and event blocks your team can reuse every issue. Responsive, tested in 50+ inboxes, from $40.`,
        eyebrow: "Newsletter Email Templates",
        h1Lead: "Custom Newsletter Email Templates",
        h1Accent: "Built for Every Issue",
        lead: "MailStora designs and codes modular newsletter email templates with reusable article, product, event and sponsor blocks, so your team can publish a polished, on-brand issue in minutes, every week.",
        cta: "Get a Newsletter Template Quote",
        trust: ["Modular content blocks", "Easy weekly publishing", "Responsive and accessible", "From $40"],
        heroImage: "/images/media/generated/newsletter-email-templates-hero.webp",
        heroAlt: "Newsletter template built from reusable blocks, shown on laptop and phone",
        whatTitle: "What Is a Modular Newsletter Email Template?",
        what: [
            "A modular newsletter email template is a reusable newsletter layout made of interchangeable blocks, such as a featured story, article list, product row, event card and sponsor slot. Each issue is built by arranging and filling blocks, not redesigning the email.",
            `MailStora plans the block library around your content, codes it for your email platform and tests it in 50+ clients so long, content-heavy newsletters stay readable and avoid Gmail clipping. Every template is built by ${founderLine}.`,
        ],
        facts: [
            { label: "Starting price", value: "$40 per template" },
            { label: "Delivery time", value: stats.turnaround },
            { label: "Blocks", value: "Feature, articles, products, events, sponsors" },
            { label: "Platforms", value: "Mailchimp, Klaviyo, HubSpot, Beehiiv and more" },
            { label: "File size", value: "Kept under Gmail's clipping limit" },
            { label: "Testing", value: "50+ email clients, light and dark mode" },
        ],
        priceFrom: "40",
        processLabel: "Newsletter Template",
        process: [
            { title: "Plan your content", text: "Your typical issue is reviewed and the block library is planned." },
            { title: "Design and code", text: "Each block is designed and coded to work in any order." },
            { title: "Test long issues", text: "Full issues are tested in 50+ clients and checked for Gmail clipping." },
            { title: "Set up in your ESP", text: "The template is uploaded with editable, reusable blocks." },
        ],
        platformsEyebrow: "Newsletter Template Compatibility",
        platformsTitle: "Newsletter Templates for Every Email Platform",
        platformsSubtitle: "Coded for your newsletter platform and tested in the inboxes your readers use.",
        platforms: ["Mailchimp", "Klaviyo", "HubSpot", "Beehiiv", "Substack", "Campaign Monitor", "Brevo"],
        showPricing: true,
        related: ["html-email-template-development", "mailchimp-email-templates", "hubspot-email-templates", "transactional-email-templates"],
        faqIntro: "Answers about custom newsletter email templates.",
        faqs: [
            { q: "What blocks should a newsletter template include?", a: "Most newsletter templates include a header, featured story, article list, image and text rows, product or event cards, a sponsor slot, social links and a footer. MailStora plans blocks around the content you actually publish." },
            { q: "How do I stop Gmail clipping my newsletter?", a: "Gmail clips emails with more than about 102KB of HTML. MailStora keeps newsletter code lean so long issues display in full." },
            { q: "Can we build each issue ourselves?", a: "Yes. Blocks are set up as editable, reusable sections in your email platform, so your team can build every issue without a developer." },
            { q: "Which newsletter platforms do you support?", a: "Newsletter templates can be built for Mailchimp, Klaviyo, HubSpot, Beehiiv, Campaign Monitor, Brevo and most platforms that accept custom HTML." },
            { q: "How much does a newsletter template cost?", a: `A custom newsletter template starts at $40 and is usually delivered in ${stats.turnaround}. Larger block libraries are quoted per project.` },
            { q: "Are newsletter templates accessible?", a: "Yes. Templates use real text instead of text in images, readable font sizes, colour contrast checks and alt text, which also helps deliverability." },
            { q: "Can you redesign our existing newsletter?", a: "Yes. An existing newsletter can be redesigned and rebuilt as a cleaner, modular template that is easier to publish." },
        ],
        rich: {
            labels: {
                pains: ["Common Newsletter Problems", "Newsletter Problems That Lose Readers"],
                benefits: "Why Choose MailStora for Newsletter Templates",
                projects: ["Newsletter Template Portfolio", "Newsletter Email Templates", "We Have Built"],
                overview: "Newsletter Template Basics",
                process: ["Newsletter Template Process", "How We Build Your Newsletter Template"],
                related: ["Related Email Services", "More Email Services", "From MailStora"],
            },
            cta: quoteCta("Newsletter Email Templates", "Get a Newsletter Template You Can Publish in Minutes", "Share a recent issue and get a free quote within 24 hours. Templates from $40.", "Get a Newsletter Template Quote"),
            intro: {
                eyebrow: "Newsletter Template Design",
                titleLead: "Newsletter Templates That Make",
                titleAccent: "Every Issue Easy",
                text: [
                    "A newsletter goes out every week or month, so a template that is slow to fill or looks cramped on mobile costs time on every issue and quietly loses readers.",
                    "MailStora builds modular newsletter templates with a clear reading hierarchy and reusable blocks, so your team drops in stories, products and events and sends a polished issue in minutes.",
                ],
                image: "/images/media/generated/newsletter-email-templates-intro.webp",
                alt: "Newsletter blocks: featured story, article rows, event and sponsor blocks forming an issue",
                image2: "/images/media/generated/newsletter-email-templates-phone.webp",
                alt2: "Newsletter email on a phone",
                features: [
                    { title: "Modular blocks", text: "Feature, article, product, event and sponsor blocks in any order." },
                    { title: "Clear reading hierarchy", text: "Layouts that guide readers from headline to click." },
                    { title: "Lean code", text: "Long issues stay under Gmail's clipping limit." },
                    { title: "Accessible by design", text: "Live text, contrast and alt text for every reader." },
                ],
            },
            pains: {
                title: "Newsletter Problems That Lose Readers",
                subtitle: "Editors and marketers usually come to us with one of these problems.",
                items: [
                    { title: "Every issue takes hours", text: "No reusable blocks, so the newsletter is rebuilt each time." },
                    { title: "Gmail clips the email", text: "Long issues get cut off behind a View entire message link." },
                    { title: "Hard to read on mobile", text: "Dense columns and small text push mobile readers away." },
                    { title: "The design feels dated", text: "An old template that no longer matches the brand." },
                ],
            },
            offer: {
                title: "Custom Newsletter Email Template",
                text: "A modular, on-brand newsletter template with reusable blocks, lean code and full testing, set up in your email platform.",
                priceLabel: "Starting at",
                price: "$40",
                priceNote: "per template, one-time",
                cta: "Get a Newsletter Template Quote",
                image: "/images/media/generated/newsletter-email-templates-offer.webp",
                alt: "Custom newsletter template: block library, lean code and accessible design",
                items: [
                    "Custom newsletter design",
                    "Reusable content block library",
                    "Featured story and article rows",
                    "Product, event and sponsor blocks",
                    "Responsive mobile layout",
                    "Lean code to avoid Gmail clipping",
                    "Set up in your email platform",
                    `Delivered in ${stats.turnaround}`,
                ],
            },
            benefits: { titleLead: "Newsletter Email Templates", titleAccent: "Without the Headaches", subtitle: "One developer who builds newsletter systems your team can run every week.", items: benefitItems("newsletter template") },
            projects: {
                subtitle: "Newsletters built for content marketers, brands and communities.",
                items: [
                    { src: IMG + "mailstora-weekly-newsletter-email.webp", alt: "Weekly marketing newsletter", caption: "Weekly newsletter" },
                    { src: IMG + "newsletter-email-template-coffee.webp", alt: "Coffee brand newsletter", caption: "Brand newsletter" },
                    { src: IMG + "mailstora-marketing-tips-email-template.webp", alt: "Marketing tips newsletter", caption: "Tips newsletter" },
                    { src: IMG + "corporate-newsletter-email-signature.webp", alt: "Corporate newsletter", caption: "Corporate newsletter" },
                ],
            },
        },
        consultTopic: "Newsletter",
    }),

    /* ───────────────────────── Transactional email templates ───────────────────────── */
    "transactional-email-templates": spoke({
        name: "Transactional Email Templates",
        serviceType: "Transactional email template development",
        summary: "Order, shipping, password and account emails that are clear and on-brand.",
        metaTitle: "Custom Transactional Email Templates | MailStora",
        metaDescription: "Transactional email templates for order confirmations, shipping updates, password resets and receipts. On-brand and ready for Shopify, SendGrid and Postmark.",
        eyebrow: "Transactional Email Templates",
        h1Lead: "Custom Transactional Email Templates",
        h1Accent: "Customers Actually Read",
        lead: "MailStora designs and codes transactional email templates, including order confirmations, shipping updates, password resets and receipts, that are clear, on-brand and ready for Shopify or your sending service.",
        cta: "Get a Transactional Template Quote",
        trust: ["Order, shipping and account emails", "Dynamic data variables", "Shopify, SendGrid, Postmark", "From $40"],
        heroImage: "/images/media/generated/transactional-email-templates-hero.webp",
        heroAlt: "Order confirmation email on laptop and phone, part of a full order update system",
        whatTitle: "What Are Transactional Email Templates?",
        what: [
            "Transactional email templates are the automated emails a customer receives after an action: order confirmations, shipping and delivery updates, receipts, password resets, account verification and similar messages. They have some of the highest open rates of any email, so their design directly shapes customer trust.",
            `MailStora builds each transactional template with the data variables your platform uses, such as Shopify Liquid, SendGrid Handlebars or Postmark Mustachio, and tests every state with real sample data. Every template is led and quality-checked by ${founderLine}.`,
        ],
        facts: [
            { label: "Starting price", value: "$40 per template" },
            { label: "Delivery time", value: stats.turnaround },
            { label: "Email types", value: "Orders, shipping, receipts, passwords, accounts" },
            { label: "Platforms", value: "Shopify, SendGrid, Postmark, Mailgun, Klaviyo" },
            { label: "Data", value: "Liquid, Handlebars or Mustachio variables" },
            { label: "Testing", value: "50+ email clients with sample data" },
        ],
        priceFrom: "40",
        processLabel: "Transactional Template",
        process: [
            { title: "List your emails", text: "Every transactional email and its data fields are mapped." },
            { title: "Design one system", text: "A shared layout keeps every notification consistent and on-brand." },
            { title: "Code with variables", text: "Templates are coded with your platform's data variables." },
            { title: "Test every state", text: "Each email is tested with sample data in 50+ clients." },
        ],
        platformsEyebrow: "Transactional Email Platforms",
        platformsTitle: "Transactional Templates for Stores and Apps",
        platformsSubtitle: "Built for the ecommerce platforms and sending services that power your notifications.",
        platforms: ["Shopify", "WooCommerce", "SendGrid", "Postmark", "Mailgun", "Amazon SES", "Klaviyo"],
        showPricing: true,
        related: ["html-email-template-development", "klaviyo-email-templates", "newsletter-email-templates", "outlook-email-rendering-fix"],
        faqIntro: "Answers about custom transactional email templates.",
        faqs: [
            { q: "What is a transactional email?", a: "A transactional email is an automated message triggered by a customer's action, such as an order confirmation, shipping update, receipt or password reset. It is sent to one person, not a marketing list." },
            { q: "Can you customise Shopify notification emails?", a: "Yes. MailStora redesigns Shopify's order, shipping and customer notification templates using Shopify Liquid, keeping all order data working correctly." },
            { q: "Do you build templates for SendGrid and Postmark?", a: "Yes. Templates are built with SendGrid Handlebars, Postmark Mustachio or Mailgun variables, so developers can plug them straight into your app." },
            { q: "Which transactional emails do I need?", a: "Most stores need order confirmation, shipping, delivery, refund and account emails. SaaS products usually need welcome, verification, password reset, receipt and billing emails." },
            { q: "Can transactional emails include marketing content?", a: "A small cross-sell or referral block can be added, but transactional emails should stay focused on the transaction to protect deliverability and meet email rules." },
            { q: "How much do transactional email templates cost?", a: "A single transactional template starts at $40. A full set of order and account emails is quoted as a package." },
            { q: "Are transactional templates tested with real data?", a: "Yes. Every template is tested with sample data for each state, such as multiple items, discounts and long addresses, in 50+ email clients." },
        ],
        rich: {
            labels: {
                pains: ["Common Transactional Email Problems", "Transactional Email Problems That Hurt Trust"],
                benefits: "Why Choose MailStora for Transactional Emails",
                projects: ["Transactional Email Portfolio", "Transactional Email Templates", "We Have Built"],
                overview: "Transactional Email Basics",
                process: ["Transactional Email Process", "How We Build Your Transactional Emails"],
                related: ["Related Email Services", "More Email Services", "From MailStora"],
            },
            cta: quoteCta("Transactional Email Templates", "Get Order and Account Emails That Build Trust", "List the emails you need and get a free quote within 24 hours. Templates from $40.", "Get a Transactional Template Quote"),
            intro: {
                eyebrow: "Transactional Email Design",
                titleLead: "Transactional Emails That Look",
                titleAccent: "as Good as Your Brand",
                text: [
                    "Order confirmations and receipts are the emails customers open most, yet many stores and apps still send the plain default versions. They look untrustworthy and waste the best chance to bring customers back.",
                    "MailStora designs one consistent system for every transactional email, codes it with your platform's data variables and tests every state, so each notification is clear, reassuring and on-brand.",
                ],
                image: "/images/media/generated/transactional-email-templates-intro.webp",
                alt: "Order confirmation email on a phone with order confirmed, shipped and delivered states",
                image2: "/images/media/generated/transactional-email-templates-phone.webp",
                alt2: "Order confirmation email on a phone",
                features: [
                    { title: "One consistent system", text: "Every notification shares the same brand layout." },
                    { title: "Dynamic data variables", text: "Order, customer and account data from your platform." },
                    { title: "Clear, scannable layout", text: "Totals, dates and next steps customers find instantly." },
                    { title: "Tested every state", text: "Multiple items, discounts and long addresses checked." },
                ],
            },
            pains: {
                title: "Transactional Email Problems That Hurt Trust",
                subtitle: "Stores and SaaS teams usually come to us with one of these problems.",
                items: [
                    { title: "Default emails look untrustworthy", text: "Plain platform templates that do not match the brand." },
                    { title: "Every email looks different", text: "Order, shipping and account emails built at different times." },
                    { title: "Data breaks the layout", text: "Long product names or many items push the design apart." },
                    { title: "Customers cannot find key details", text: "Totals, tracking links and next steps buried in text." },
                ],
            },
            offer: {
                title: "Transactional Email Template Set",
                text: "A consistent set of on-brand transactional templates coded with your platform's variables and tested with real sample data.",
                priceLabel: "Starting at",
                price: "$40",
                priceNote: "per template, sets quoted",
                cta: "Get a Transactional Template Quote",
                image: "/images/media/generated/transactional-email-templates-offer.webp",
                alt: "Transactional email set: Shopify Liquid, every order state and one consistent system",
                items: [
                    "Order confirmation and receipt",
                    "Shipping and delivery updates",
                    "Password reset and verification",
                    "Account and billing emails",
                    "Shopify Liquid or ESP variables",
                    "Responsive, accessible layout",
                    "Tested with sample data",
                    "Developer-ready handover",
                ],
            },
            benefits: { titleLead: "Transactional Email Templates", titleAccent: "Without the Headaches", subtitle: "One developer who speaks both design and platform variables.", items: benefitItems("transactional template") },
            projects: {
                subtitle: "Order, onboarding and account emails built for stores and SaaS products.",
                items: [
                    { src: IMG + "mailstora-order-confirmation-email.webp", alt: "Order confirmation email", caption: "Order confirmation" },
                    { src: IMG + "mailstora-welcome-email.webp", alt: "Account welcome email", caption: "Account welcome" },
                    { src: IMG + "saas-product-update-email-template.webp", alt: "SaaS account email", caption: "SaaS notification" },
                ],
            },
        },
        consultTopic: "Transactional Email",
    }),

    /* ───────────────────────── Gmail email signature ───────────────────────── */
    "gmail-email-signature": spoke({
        name: "Gmail Email Signatures",
        serviceType: "Gmail HTML email signature design",
        summary: "HTML signatures for Gmail and Google Workspace, with install guide.",
        metaTitle: "Gmail Email Signature Design (HTML) | MailStora",
        metaDescription: "Gmail email signature design: clickable HTML signatures for Gmail and Google Workspace with logos, photos and social icons, sharp on any device. From $25.",
        eyebrow: "Gmail Email Signatures",
        h1Lead: "Gmail Email Signature Design",
        h1Accent: "for Gmail and Google Workspace",
        lead: "MailStora designs clickable HTML email signatures built for Gmail and Google Workspace, with hosted logos, photos and social icons that stay sharp on desktop and the Gmail app, plus a simple install guide.",
        cta: "Order a Gmail Signature",
        trust: ["Gmail and Google Workspace", "Works in the Gmail app", "Install guide included", "From $25"],
        heroImage: "/images/media/generated/gmail-email-signature-hero.webp",
        heroAlt: "HTML signature pasted into Gmail settings and shown in a Gmail message",
        whatTitle: "What Is an HTML Email Signature for Gmail?",
        what: [
            "An HTML email signature for Gmail is a branded signature built in HTML and pasted into Gmail's signature settings, so it can include your logo, photo, clickable contact links and social icons. Gmail's editor strips many styles, so the signature must be coded specifically to survive it.",
            `MailStora builds Gmail signatures with hosted images and Gmail-safe inline code, and provides step-by-step setup for Gmail and Google Workspace accounts. Every signature is designed by ${founderLine}.`,
        ],
        facts: [
            { label: "Starting price", value: "$25 per signature" },
            { label: "Works in", value: "Gmail web, Gmail app, Google Workspace" },
            { label: "Elements", value: "Logo, photo, links, social icons, banner" },
            { label: "Images", value: "Hosted, retina-ready" },
            { label: "Setup", value: "Step-by-step Gmail install guide" },
            { label: "Delivery time", value: stats.turnaround },
        ],
        priceFrom: "25",
        processLabel: "Gmail Signature",
        process: [
            { title: "Send your details", text: "Share your logo, photo, colours and contact links." },
            { title: "Design", text: "You review and approve the signature design." },
            { title: "Code for Gmail", text: "The signature is coded with Gmail-safe inline HTML and hosted images." },
            { title: "Install", text: "Paste it in with the install guide, or we set it up with you." },
        ],
        platformsEyebrow: "Gmail Signature Compatibility",
        platformsTitle: "Gmail Signatures That Look Right Everywhere",
        platformsSubtitle: "Set up in Gmail, then checked in the inboxes your contacts read it in.",
        platforms: ["Gmail web", "Gmail for iOS", "Gmail for Android", "Google Workspace", "Outlook", "Apple Mail"],
        showPricing: true,
        related: ["html-email-signature-design", "outlook-email-signature", "html-email-template-development", "white-label-email-development"],
        faqIntro: "Answers about HTML email signatures for Gmail.",
        faqs: [
            { q: "How do I add an HTML signature to Gmail?", a: "Open the signature in a browser, copy it, then paste it into Gmail under Settings, See all settings, General, Signature. MailStora includes a step-by-step guide with screenshots." },
            { q: "Why does my Gmail signature look different in other inboxes?", a: "Gmail's signature editor strips some styles, and images that are not hosted can be blocked. MailStora codes signatures with Gmail-safe inline styles and hosted images so they look the same everywhere." },
            { q: "Does the signature work in the Gmail mobile app?", a: "The Gmail app uses a separate plain-text signature by default. Emails sent from the app can use the desktop HTML signature when the mobile signature setting is turned off." },
            { q: "Can you set up signatures for our whole Google Workspace team?", a: "Yes. Individual versions are created for each staff member, and Workspace admins can deploy them centrally with a signature management tool." },
            { q: "How much does a Gmail signature cost?", a: "A Gmail HTML email signature starts at $25, and a signature with a promotional banner is $65. Team packages are quoted per project." },
            { q: "Why do images in my Gmail signature not show?", a: "Images pasted directly or linked from private storage often fail. MailStora hosts signature images on a public, reliable URL so they load for every recipient." },
        ],
        rich: {
            labels: {
                pains: ["Common Gmail Signature Problems", "Gmail Signature Problems We Fix"],
                benefits: "Why Choose MailStora for Gmail Signatures",
                projects: ["Email Signature Portfolio", "HTML Email Signatures", "We Have Designed"],
                overview: "Gmail Signature Basics",
                process: ["Gmail Signature Process", "How We Create Your Gmail Signature"],
                related: ["Related Signature Services", "More Signature Services", "From MailStora"],
            },
            cta: quoteCta("Gmail Email Signatures", "Get a Gmail Signature That Looks Professional in Every Inbox", "Send your logo and details and get a free quote within 24 hours. From $25.", "Order a Gmail Signature"),
            intro: {
                eyebrow: "Gmail Signature Design",
                titleLead: "Gmail Signatures That Survive",
                titleAccent: "Gmail's Editor",
                text: [
                    "Gmail's signature editor is simple, but it strips formatting, resizes images and breaks layouts copied from other tools. Many Gmail signatures end up with blurry logos, broken links or missing icons.",
                    "MailStora codes your signature specifically for Gmail with inline styles and hosted, retina-ready images, so it looks sharp for every recipient, on desktop and mobile.",
                ],
                image: "/images/media/generated/gmail-email-signature-intro.webp",
                alt: "Gmail signature that keeps its layout in Gmail's editor",
                image2: "/images/media/generated/gmail-email-signature-phone.webp",
                alt2: "Gmail signature on a phone",
                features: [
                    { title: "Gmail-safe code", text: "Inline HTML that Gmail's editor keeps intact." },
                    { title: "Hosted, sharp images", text: "Logos and photos that load and stay crisp." },
                    { title: "Clickable links", text: "Phone, email, website and social links that work." },
                    { title: "Workspace ready", text: "Team versions for Google Workspace accounts." },
                ],
            },
            pains: {
                title: "Gmail Signature Problems We Fix",
                subtitle: "If your Gmail signature has any of these issues, recipients notice.",
                items: [
                    { title: "Logo looks blurry or huge", text: "Gmail resizes images that are not sized correctly." },
                    { title: "Images do not load", text: "Pasted or privately hosted images show as broken boxes." },
                    { title: "Layout falls apart", text: "Signatures copied from Word or Canva lose their structure." },
                    { title: "Team signatures do not match", text: "Every Workspace user has a slightly different version." },
                ],
            },
            offer: {
                title: "Custom Gmail Email Signature",
                text: "A clickable, on-brand HTML signature coded for Gmail and Google Workspace, with hosted images and an install guide.",
                priceLabel: "Starting at",
                price: "$25",
                priceNote: "per signature, one-time",
                cta: "Order a Gmail Signature",
                image: "/images/media/generated/gmail-email-signature-offer.webp",
                alt: "Custom Gmail signature: Gmail-safe code, Google Workspace ready and clickable",
                items: [
                    "Custom signature design",
                    "Gmail-safe inline HTML",
                    "Hosted retina-ready images",
                    "Clickable contact and social links",
                    "Optional promotional banner",
                    "Tested in Gmail, Outlook and Apple Mail",
                    "Step-by-step Gmail install guide",
                    "Google Workspace team versions",
                ],
            },
            benefits: { titleLead: "Gmail Email Signatures", titleAccent: "Without the Headaches", subtitle: "One designer-developer who knows every Gmail signature quirk.", items: benefitItems("signature") },
            projects: {
                subtitle: "HTML email signatures designed for Gmail and Google Workspace users.",
                items: [
                    { src: IMG + "mailstora-html-email-signature.webp", alt: "Gmail signature with banner", caption: "Signature with banner" },
                    { src: IMG + "corporate-newsletter-email-signature.webp", alt: "Corporate Gmail signature", caption: "Corporate signature" },
                ],
            },
        },
        consultTopic: "Email Signature",
    }),

    /* ───────────────────────── Outlook email signature ───────────────────────── */
    "outlook-email-signature": spoke({
        name: "Outlook Email Signatures",
        serviceType: "Outlook HTML email signature design",
        summary: "Signatures for new and classic Outlook, Microsoft 365 and Outlook mobile.",
        metaTitle: "Outlook Email Signature Design (HTML) | MailStora",
        metaDescription: "Outlook email signature design: HTML signatures for classic and new Outlook, Outlook on the web, Mac and mobile, plus Microsoft 365 team rollout. From $25.",
        eyebrow: "Outlook Email Signatures",
        h1Lead: "Outlook Email Signature Design",
        h1Accent: "for New and Classic Outlook",
        lead: "MailStora designs HTML email signatures that work in classic Outlook for Windows, the new Outlook, Outlook on the web and Outlook mobile, with Microsoft 365 team rollout support and a clear install guide.",
        cta: "Order an Outlook Signature",
        trust: ["Classic and new Outlook", "Microsoft 365 ready", "No stretched logos", "From $25"],
        heroImage: "/images/media/generated/outlook-email-signature-hero.webp",
        heroAlt: "HTML signature in Outlook, tested in classic Outlook, new Outlook, Outlook on the web and Outlook for Mac",
        whatTitle: "What Is an HTML Email Signature for Outlook?",
        what: [
            "An HTML email signature for Outlook is a branded signature built to display correctly in Microsoft Outlook, which renders HTML with Microsoft Word's engine in its classic Windows version. Signatures that are not coded for Outlook often show stretched logos, extra spacing and broken columns.",
            `MailStora codes each Outlook signature with table-based HTML and fixed image sizes, installs it for classic and new Outlook, and supports company-wide rollout through Microsoft 365. Every signature is designed by ${founderLine}.`,
        ],
        facts: [
            { label: "Starting price", value: "$25 per signature" },
            { label: "Works in", value: "Classic Outlook, new Outlook, web, Mac, mobile" },
            { label: "Rollout", value: "Microsoft 365 team deployment" },
            { label: "Images", value: "Fixed-size, hosted, retina-ready" },
            { label: "Setup", value: "Install guide for each Outlook version" },
            { label: "Delivery time", value: stats.turnaround },
        ],
        priceFrom: "25",
        processLabel: "Outlook Signature",
        process: [
            { title: "Send your details", text: "Share your logo, photo, colours and contact links." },
            { title: "Design", text: "You review and approve the signature design." },
            { title: "Code for Outlook", text: "Table-based HTML with fixed image sizes that Outlook respects." },
            { title: "Install or roll out", text: "Install per user, or deploy across Microsoft 365." },
        ],
        platformsEyebrow: "Outlook Signature Compatibility",
        platformsTitle: "Outlook Signatures for Every Version",
        platformsSubtitle: "Tested in each Outlook version your team uses and in the inboxes your contacts read.",
        platforms: ["Classic Outlook (Windows)", "New Outlook", "Outlook on the web", "Outlook for Mac", "Outlook mobile", "Microsoft 365", "Gmail"],
        showPricing: true,
        related: ["html-email-signature-design", "gmail-email-signature", "outlook-email-rendering-fix", "html-email-template-development"],
        faqIntro: "Answers about HTML email signatures for Outlook.",
        faqs: [
            { q: "Why does my signature look broken in Outlook?", a: "Classic Outlook for Windows renders HTML with Microsoft Word's engine, which ignores many styles and resizes images. MailStora codes signatures with table-based HTML and fixed image dimensions so Outlook displays them correctly." },
            { q: "Does the signature work in the new Outlook?", a: "Yes. Signatures are set up and tested in both classic Outlook and the new Outlook for Windows, as well as Outlook on the web, Mac and mobile." },
            { q: "How do I install an HTML signature in Outlook?", a: "Each Outlook version has its own signature settings. MailStora provides a step-by-step guide for classic Outlook, new Outlook, Outlook on the web and Mac." },
            { q: "Can you roll out signatures for our whole company in Microsoft 365?", a: "Yes. Individual signatures can be created for every employee, and Microsoft 365 admins can deploy them centrally with a transport rule or a signature management tool." },
            { q: "Why does Outlook make my logo huge?", a: "Outlook ignores CSS sizing on some images and shows them at their original size. MailStora sets exact width and height attributes so logos stay the right size." },
            { q: "How much does an Outlook signature cost?", a: "An Outlook HTML email signature starts at $25, and a signature with a promotional banner is $65. Company-wide packages are quoted per project." },
        ],
        rich: {
            labels: {
                pains: ["Common Outlook Signature Problems", "Outlook Signature Problems We Fix"],
                benefits: "Why Choose MailStora for Outlook Signatures",
                projects: ["Email Signature Portfolio", "HTML Email Signatures", "We Have Designed"],
                overview: "Outlook Signature Basics",
                process: ["Outlook Signature Process", "How We Create Your Outlook Signature"],
                related: ["Related Signature Services", "More Signature Services", "From MailStora"],
            },
            cta: quoteCta("Outlook Email Signatures", "Get an Outlook Signature That Never Breaks", "Send your logo and details and get a free quote within 24 hours. From $25.", "Order an Outlook Signature"),
            intro: {
                eyebrow: "Outlook Signature Design",
                titleLead: "Outlook Signatures Coded for",
                titleAccent: "Every Outlook Version",
                text: [
                    "Outlook is where most email signatures break. Classic Outlook stretches logos, adds random spacing and ignores modern styles, and the new Outlook handles signatures differently again.",
                    "MailStora codes your signature specifically for Outlook, tests it in every version your team uses and helps you roll it out across Microsoft 365, so every employee sends a consistent, professional signature.",
                ],
                image: "/images/media/generated/outlook-email-signature-intro.webp",
                alt: "Outlook email signature coded to work in every Outlook version",
                image2: "/images/media/generated/outlook-email-signature-phone.webp",
                alt2: "Outlook signature on a phone",
                features: [
                    { title: "Outlook-safe tables", text: "Layouts that classic Outlook's Word engine respects." },
                    { title: "Fixed-size images", text: "Logos and photos that never stretch or shrink." },
                    { title: "Every Outlook version", text: "Classic, new, web, Mac and mobile tested." },
                    { title: "Microsoft 365 rollout", text: "Consistent signatures for every employee." },
                ],
            },
            pains: {
                title: "Outlook Signature Problems We Fix",
                subtitle: "These are the Outlook signature issues companies ask us to solve most.",
                items: [
                    { title: "Logo shows at full size", text: "Outlook ignores CSS sizing and blows images up." },
                    { title: "Extra gaps and lines", text: "Word's rendering engine adds spacing and borders." },
                    { title: "Broken in the new Outlook", text: "A signature that worked in classic Outlook fails in the new app." },
                    { title: "Every employee differs", text: "No central rollout, so signatures drift apart." },
                ],
            },
            offer: {
                title: "Custom Outlook Email Signature",
                text: "A clickable, on-brand HTML signature coded for every Outlook version, with install guides and Microsoft 365 rollout support.",
                priceLabel: "Starting at",
                price: "$25",
                priceNote: "per signature, one-time",
                cta: "Order an Outlook Signature",
                image: "/images/media/generated/outlook-email-signature-offer.webp",
                alt: "Custom Outlook signature: every Outlook version, fixed-size images and team rollout",
                items: [
                    "Custom signature design",
                    "Outlook-safe table-based HTML",
                    "Fixed-size, retina-ready images",
                    "Clickable contact and social links",
                    "Classic and new Outlook tested",
                    "Outlook web, Mac and mobile checked",
                    "Install guide for each version",
                    "Microsoft 365 team rollout",
                ],
            },
            benefits: { titleLead: "Outlook Email Signatures", titleAccent: "Without the Headaches", subtitle: "One developer who has solved every Outlook signature quirk.", items: benefitItems("signature") },
            projects: {
                subtitle: "HTML email signatures designed for Outlook and Microsoft 365 teams.",
                items: [
                    { src: IMG + "corporate-newsletter-email-signature.webp", alt: "Corporate Outlook signature", caption: "Corporate signature" },
                    { src: IMG + "mailstora-html-email-signature.webp", alt: "Outlook signature with banner", caption: "Signature with banner" },
                ],
            },
        },
        consultTopic: "Email Signature",
    }),

    /* ───────────────────────── White-label email development ───────────────────────── */
    "white-label-email-development": spoke({
        name: "White-Label Email Development",
        serviceType: "White-label HTML email development for agencies",
        summary: "HTML email production for agencies, delivered under your brand.",
        metaTitle: "White-Label Email Development for Agencies | MailStora",
        metaDescription: "White-label email development for agencies: hand-coded templates, Klaviyo builds and email QA delivered under your brand. NDA on request, no MailStora branding.",
        eyebrow: "White-Label for Agencies",
        h1Lead: "White-Label Email Development",
        h1Accent: "for Marketing Agencies",
        lead: "MailStora is the behind-the-scenes email developer for marketing agencies: hand-coded templates, Klaviyo and ESP builds and email QA, delivered under your brand, on your timeline, with no MailStora branding.",
        cta: "Become a Partner Agency",
        trust: ["No MailStora branding", "NDA available", "Agency-friendly turnaround", "Works in your clients' ESPs"],
        heroImage: "/images/media/generated/white-label-email-development-hero.webp",
        heroAlt: "White-label email delivered under your agency's brand: no MailStora branding, NDA on request, QA in 50+ clients",
        whatTitle: "What Is White-Label Email Development?",
        what: [
            "White-label email development means an agency outsources email coding and production to a specialist, then delivers the work to its clients under the agency's own brand. The client never sees the developer, and the agency keeps the relationship and the margin.",
            `MailStora works as an extension of your team: we code designs from your designers, build templates in your clients' Klaviyo, Mailchimp or HubSpot accounts and QA every email, with no MailStora branding anywhere. Every project is handled by ${founderLine}.`,
        ],
        facts: [
            { label: "Branding", value: "None: delivered under your agency" },
            { label: "Services", value: "Templates, conversions, ESP builds, QA" },
            { label: "Platforms", value: "Klaviyo, Mailchimp, HubSpot and more" },
            { label: "Confidentiality", value: "NDA available" },
            { label: "Communication", value: "Slack, email, WhatsApp or Upwork" },
            { label: "Pricing", value: "Per project or monthly retainer" },
        ],
        processLabel: "White-Label",
        process: [
            { title: "Onboard", text: "We learn your workflow, tools, brand rules and QA standards." },
            { title: "Receive the brief", text: "Send designs and client details through your usual channel." },
            { title: "Build and QA", text: "Emails are coded, built in the client's ESP and tested in 50+ clients." },
            { title: "Deliver under your brand", text: "You receive finished work to present as your own." },
        ],
        platformsEyebrow: "Agency Platforms",
        platformsTitle: "We Work in Your Clients' Email Platforms",
        platformsSubtitle: "Templates and builds are delivered in whichever email platform each client uses.",
        platforms: ["Klaviyo", "Mailchimp", "HubSpot", "Brevo", "ActiveCampaign", "Campaign Monitor", "Salesforce Marketing Cloud"],
        showPricing: false,
        related: ["html-email-template-development", "figma-to-html-email", "klaviyo-flow-setup", "outlook-email-rendering-fix"],
        faqIntro: "Answers about white-label email development for agencies.",
        faqs: [
            { q: "Will my clients know I use MailStora?", a: "No. Work is delivered with no MailStora branding in code, files or emails, and communication can go only through your agency. An NDA is available." },
            { q: "What can you produce under white label?", a: "MailStora produces HTML email templates, Figma and PSD to HTML conversions, Klaviyo, Mailchimp and HubSpot builds, email signatures and email QA and testing for agencies." },
            { q: "Can you work inside our clients' ESP accounts?", a: "Yes. With user access, templates and flows are built directly in each client's Klaviyo, Mailchimp, HubSpot or other platform." },
            { q: "How does pricing work for agencies?", a: "Agencies can pay per project or book a monthly retainer with a set number of emails, which lets you plan margins in advance." },
            { q: "Can you meet tight agency deadlines?", a: `Most templates are delivered in ${stats.turnaround}, and priority slots can be agreed for partner agencies with regular work.` },
            { q: "Do you communicate through our tools?", a: "Yes. MailStora can work in your Slack, project management tool or email threads, following your existing process." },
        ],
        rich: {
            labels: {
                pains: ["Common Agency Email Problems", "Email Production Problems Agencies Face"],
                benefits: "Why Agencies Choose MailStora",
                projects: ["White-Label Email Portfolio", "Emails We Have Built", "for Agencies"],
                overview: "White-Label Email Basics",
                process: ["White-Label Email Process", "How We Work With Your Agency"],
                related: ["Related Email Services", "More Email Services", "From MailStora"],
            },
            cta: quoteCta("White-Label Email Development", "Add an Email Developer to Your Agency Without Hiring", "Tell us about your agency and clients and get partner pricing within 24 hours.", "Become a Partner Agency"),
            intro: {
                eyebrow: "Agency Email Production",
                titleLead: "Your Behind-the-Scenes",
                titleAccent: "Email Development Team",
                text: [
                    "Email is one of the most technical deliverables an agency sells. Hiring an in-house email developer is expensive, and generalist web developers often ship emails that break in Outlook and damage client trust.",
                    "MailStora gives your agency a specialist email developer on demand. Your designers design, we code, build and QA, and you deliver polished email work under your own brand.",
                ],
                image: "/images/media/generated/white-label-email-development-intro.webp",
                alt: "Email built under your agency's brand with an NDA and no MailStora logo",
                image2: "/images/media/generated/white-label-email-development-phone.webp",
                alt2: "White-label client email on a phone",
                features: [
                    { title: "Fully white-labelled", text: "No MailStora branding in code, files or emails." },
                    { title: "Works in your process", text: "Your tools, your channels, your QA standards." },
                    { title: "Every ESP covered", text: "Klaviyo, Mailchimp, HubSpot and more." },
                    { title: "Scales with demand", text: "Per project or monthly capacity as your clients grow." },
                ],
            },
            pains: {
                title: "Email Production Problems Agencies Face",
                subtitle: "Agencies usually partner with us after one of these starts hurting client work.",
                items: [
                    { title: "Web developers break emails", text: "Generalist code that falls apart in Outlook and Gmail." },
                    { title: "Hiring is too expensive", text: "Not enough email work to justify a full-time specialist." },
                    { title: "Deadlines slip", text: "Email coding becomes the bottleneck before every launch." },
                    { title: "Freelancers are unreliable", text: "Inconsistent quality and slow replies put clients at risk." },
                ],
            },
            offer: {
                title: "White-Label Email Partnership",
                text: "Specialist HTML email production for your agency, delivered under your brand, per project or on a monthly retainer.",
                priceLabel: "Pricing",
                price: "Partner",
                priceNote: "per project or retainer",
                cta: "Become a Partner Agency",
                image: "/images/media/generated/white-label-email-development-offer.webp",
                alt: "White-label email partnership: NDA available, QA in 50+ clients, every email platform",
                items: [
                    "No MailStora branding",
                    "NDA available",
                    "HTML templates and conversions",
                    "Klaviyo, Mailchimp and HubSpot builds",
                    "QA in 50+ email clients",
                    "Work in your clients' accounts",
                    "Your tools and communication channels",
                    "Priority slots for partner agencies",
                ],
            },
            benefits: { titleLead: "White-Label Email Development", titleAccent: "Without the Headaches", subtitle: "A reliable specialist your agency can put in front of any client.", items: benefitItems("agency project") },
            projects: {
                subtitle: "Examples of the email work we produce for agencies and their clients.",
                items: [
                    { src: IMG + "mailstora-real-estate-email.webp", alt: "Real estate client email", caption: "Real estate client" },
                    { src: IMG + "mailstora-fashion-email.webp", alt: "Fashion client email", caption: "Fashion client" },
                    { src: IMG + "saas-software-email-design.webp", alt: "SaaS client email", caption: "SaaS client" },
                    { src: IMG + "mailstora-event-invitation-email.webp", alt: "Event client email", caption: "Event client" },
                ],
            },
        },
        consultTopic: "Agency Partnership",
    }),
};
